In [1]:
# store start time to get execution time of entire script
import time
start_time = time.time()

In [2]:
import pandas as pd
pd.set_option('display.max_rows', 500)
pd.set_option('display.max_columns', 500)
import csv

df = pd.read_csv('data_geocoded.csv')
df.head()

,Unnamed: 0,Unnamed: 0.1,ID,State,City,agyaddr,xobsyr_0,Illicit_Days5,Illicit_Cens5,female_cd,nonwhite_cd,unemplmt_cd,prsatx_cd,gvsg_cd,CWSg_0_cd,srprobg_cd,dssg_0_cd,epsg_0_cd,adhdg_0_cd,cdsg_0_cd,cjsig_0_cd,lrig_0_cd,srig_0_cd,SESg_0_cd,r4ag_0_cd,nonillicit_flag,primsev_cd_1,primsev_cd_2,primsev_cd_3,primsev_cd_4,primsev_cd_5,primsev_cd_6,B2a_0g,SUDSy_0,SDSl_0,Address,lat,lng,state_name,county_FIPS,block_FIPS
0,0,1,857,OH,Cleveland,1276 West Third St. #400,2005,365,0,0,0,0,0,2,0,0,1,1,1,1,0,1,2,0,1,1,1,0,0,0,0,0,0,0,0,"1276 West Third St. #400, Cleveland, OH",41.419286,-81.701695,Ohio,39035.0,3.903511e+14
1,1,2,929,OH,Cleveland,1276 West Third St. #400,2006,354,0,0,0,0,0,1,0,1,0,1,0,1,1,0,1,0,2,1,1,0,0,0,0,0,0,3,2,"1276 West Third St. #400, Cleveland, OH",41.419286,-81.701695,Ohio,39035.0,3.903511e+14
2,2,3,951,OH,Cleveland,1276 West Third St. #400,2006,365,0,0,0,0,0,0,0,1,0,0,0,0,1,0,1,0,2,1,0,0,1,0,0,0,0,2,1,"1276 West Third St. #400, Cleveland, OH",41.419286,-81.701695,Ohio,39035.0,3.903511e+14
3,3,4,1032,OH,Cleveland,1276 West Third St. #400,2006,365,0,0,0,0,0,2,0,1,1,1,1,1,0,2,1,0,2,1,0,0,1,0,0,0,0,2,1,"1276 West Third St. #400, Cleveland, OH",41.419286,-81.701695,Ohio,39035.0,3.903511e+14
4,4,5,1039,OH,Cleveland,1276 West Third St. #400,2004,365,0,0,0,0,0,0,0,0,1,0,0,1,1,2,1,0,2,0,0,1,0,0,0,0,0,0,0,"1276 West Third St. #400, Cleveland, OH",41.419286,-81.701695,Ohio,39035.0,3.903511e+14

In [3]:
df.shape

(21264, 41)

Add Muder Data

In [4]:
murder_data = pd.read_csv('UCR-1985-2015.csv', error_bad_lines=False)
murder_data.head()

,Unnamed: 0,Agency,city,state,state_short,1985_raw_murder_num,1986_raw_murder_num,1987_raw_murder_num,1988_raw_murder_num,1989_raw_murder_num,1990_raw_murder_num,1991_raw_murder_num,1992_raw_murder_num,1993_raw_murder_num,1994_raw_murder_num,1995_raw_murder_num,1996_raw_murder_num,1997_raw_murder_num,1998_raw_murder_num,1999_raw_murder_num,2000_raw_murder_num,2001_raw_murder_num,2002_raw_murder_num,2003_raw_murder_num,2004_raw_murder_num,2005_raw_murder_num,2006_raw_murder_num,2007_raw_murder_num,2008_raw_murder_num,2009_raw_murder_num,2010_raw_murder_num,2011_raw_murder_num,2012_raw_murder_num,2013_raw_murder_num,2014_raw_murder_num,2015_raw_murder_num,1985_murder_rate,1986_murder_rate,1987_murder_rate,1988_murder_rate,1989_murder_rate,1990_murder_rate,1991_murder_rate,1992_murder_rate,1993_murder_rate,1994_murder_rate,1995_murder_rate,1996_murder_rate,1997_murder_rate,1998_murder_rate,1999_murder_rate,2000_murder_rate,2001_murder_rate,2002_murder_rate,2003_murder_rate,2004_murder_rate,2005_murder_rate,2006_murder_rate,2007_murder_rate,2008_murder_rate,2009_murder_rate,2010_murder_rate,2011_murder_rate,2012_murder_rate,2013_murder_rate,2014_murder_rate,2015_murder_rate
0,0,New York City Police Dept,New York City,New York,NY,1384.0,1582.0,1672.0,1896.0,1905.0,2245.0,2154.0,1995.0,1946.0,1561.0,1177.0,983.0,770.0,633.0,664.0,673.0,714.0,587.0,597.0,570.0,539.0,596.0,496.0,523.0,471.0,536.0,515.0,419.0,335.0,333.0,288.0,19.3,22.0,23.0,25.8,25.8,30.7,29.3,27.1,26.5,21.3,16.1,13.4,10.5,8.6,8.9,8.4,8.9,7.3,7.4,7.0,6.6,7.3,6.0,6.3,5.6,6.6,6.3,5.1,3.99,3.93,3.398656
1,1,Los Angeles Police Dept,Los Angeles,California,CA,777.0,834.0,811.0,736.0,877.0,983.0,1027.0,1094.0,1076.0,845.0,849.0,711.0,576.0,426.0,425.0,550.0,588.0,654.0,515.0,518.0,489.0,480.0,395.0,384.0,312.0,293.0,297.0,299.0,251.0,260.0,282.0,24.4,25.6,24.3,21.6,25.5,28.2,28.9,30.3,30.5,23.8,24.5,20.3,16.3,11.8,11.6,14.9,15.6,17.1,13.4,13.4,12.6,12.4,10.2,10.0,8.1,7.7,7.7,7.8,6.47,6.66,7.218235
2,2,Chicago Police Dept,Chicago,Illinois,IL,666.0,744.0,687.0,660.0,742.0,850.0,925.0,939.0,845.0,928.0,824.0,789.0,757.0,703.0,641.0,631.0,666.0,648.0,598.0,448.0,448.0,468.0,443.0,510.0,458.0,432.0,431.0,500.0,414.0,411.0,478.0,22.2,24.8,22.8,22.0,24.8,30.5,32.9,33.1,30.3,33.1,30.0,28.6,27.4,25.6,22.7,21.8,22.9,22.1,20.6,15.5,15.6,16.4,15.7,18.0,16.1,16.0,15.9,18.5,15.22,15.09,17.546945
3,3,Houston Police Dept,Houston,Texas,TX,457.0,408.0,323.0,440.0,459.0,568.0,608.0,465.0,446.0,375.0,316.0,261.0,254.0,254.0,241.0,230.0,267.0,256.0,278.0,272.0,334.0,377.0,351.0,294.0,287.0,269.0,198.0,217.0,214.0,242.0,303.0,26.2,22.9,18.6,25.5,26.8,34.8,36.5,27.4,25.9,21.3,18.2,14.7,14.1,14.1,13.3,11.8,13.4,12.5,13.6,13.3,16.3,18.2,16.2,13.1,12.6,12.8,9.2,10.0,9.81,10.90,13.649061
4,4,Philadelphia Police Dept,Philadelphia,Pennsylvania,PA,273.0,343.0,338.0,374.0,475.0,503.0,440.0,425.0,439.0,404.0,432.0,420.0,418.0,338.0,292.0,319.0,309.0,288.0,348.0,330.0,377.0,407.0,392.0,331.0,302.0,306.0,324.0,331.0,247.0,248.0,280.0,16.6,20.8,20.5,22.6,28.7,31.7,27.6,26.5,28.1,25.9,28.2,27.5,27.4,23.3,20.3,21.0,20.4,18.9,23.3,22.2,25.6,27.8,27.3,23.0,19.5,20.1,21.2,21.5,15.90,15.91,17.959517

In [5]:
cols_to_use = ['2002_raw_murder_num','2003_raw_murder_num','2004_raw_murder_num','2005_raw_murder_num',
               '2006_raw_murder_num','2007_raw_murder_num','2008_raw_murder_num','2009_raw_murder_num',
               '2010_raw_murder_num','2011_raw_murder_num','2012_raw_murder_num','city','state_short']
murder_data = murder_data[cols_to_use]

In [6]:
murder_data.shape

(290, 13)

In [7]:
murder_data.rename(columns = {'city':'City', 'state_short':'State'}, inplace = True)

In [8]:
df = pd.merge(df, murder_data, on=['City', 'State'], how='left')
df.head()

,Unnamed: 0,Unnamed: 0.1,ID,State,City,agyaddr,xobsyr_0,Illicit_Days5,Illicit_Cens5,female_cd,nonwhite_cd,unemplmt_cd,prsatx_cd,gvsg_cd,CWSg_0_cd,srprobg_cd,dssg_0_cd,epsg_0_cd,adhdg_0_cd,cdsg_0_cd,cjsig_0_cd,lrig_0_cd,srig_0_cd,SESg_0_cd,r4ag_0_cd,nonillicit_flag,primsev_cd_1,primsev_cd_2,primsev_cd_3,primsev_cd_4,primsev_cd_5,primsev_cd_6,B2a_0g,SUDSy_0,SDSl_0,Address,lat,lng,state_name,county_FIPS,block_FIPS,2002_raw_murder_num,2003_raw_murder_num,2004_raw_murder_num,2005_raw_murder_num,2006_raw_murder_num,2007_raw_murder_num,2008_raw_murder_num,2009_raw_murder_num,2010_raw_murder_num,2011_raw_murder_num,2012_raw_murder_num
0,0,1,857,OH,Cleveland,1276 West Third St. #400,2005,365,0,0,0,0,0,2,0,0,1,1,1,1,0,1,2,0,1,1,1,0,0,0,0,0,0,0,0,"1276 West Third St. #400, Cleveland, OH",41.419286,-81.701695,Ohio,39035.0,3.903511e+14,80.0,73.0,79.0,109.0,77.0,90.0,55.0,83.0,81.0,74.0,84.0
1,1,2,929,OH,Cleveland,1276 West Third St. #400,2006,354,0,0,0,0,0,1,0,1,0,1,0,1,1,0,1,0,2,1,1,0,0,0,0,0,0,3,2,"1276 West Third St. #400, Cleveland, OH",41.419286,-81.701695,Ohio,39035.0,3.903511e+14,80.0,73.0,79.0,109.0,77.0,90.0,55.0,83.0,81.0,74.0,84.0
2,2,3,951,OH,Cleveland,1276 West Third St. #400,2006,365,0,0,0,0,0,0,0,1,0,0,0,0,1,0,1,0,2,1,0,0,1,0,0,0,0,2,1,"1276 West Third St. #400, Cleveland, OH",41.419286,-81.701695,Ohio,39035.0,3.903511e+14,80.0,73.0,79.0,109.0,77.0,90.0,55.0,83.0,81.0,74.0,84.0
3,3,4,1032,OH,Cleveland,1276 West Third St. #400,2006,365,0,0,0,0,0,2,0,1,1,1,1,1,0,2,1,0,2,1,0,0,1,0,0,0,0,2,1,"1276 West Third St. #400, Cleveland, OH",41.419286,-81.701695,Ohio,39035.0,3.903511e+14,80.0,73.0,79.0,109.0,77.0,90.0,55.0,83.0,81.0,74.0,84.0
4,4,5,1039,OH,Cleveland,1276 West Third St. #400,2004,365,0,0,0,0,0,0,0,0,1,0,0,1,1,2,1,0,2,0,0,1,0,0,0,0,0,0,0,"1276 West Third St. #400, Cleveland, OH",41.419286,-81.701695,Ohio,39035.0,3.903511e+14,80.0,73.0,79.0,109.0,77.0,90.0,55.0,83.0,81.0,74.0,84.0

In [9]:
df.shape

(21264, 52)

In [10]:
import numpy as np

print(np.sort(df['xobsyr_0'].unique()))

[2002 2003 2004 2005 2006 2007 2008 2009 2010 2011 2012]

In [11]:
%%time
from tqdm.notebook import tqdm # used to show progress bar

# only keep the value that matches the year, set all other values to NaN

raw_murder_nums = ['2002_raw_murder_num','2003_raw_murder_num','2004_raw_murder_num','2005_raw_murder_num',
                   '2006_raw_murder_num','2007_raw_murder_num','2008_raw_murder_num','2009_raw_murder_num',
                   '2010_raw_murder_num','2011_raw_murder_num','2012_raw_murder_num',]

for i,row in tqdm(df.iterrows(), total=df.shape[0]):
    year = row['xobsyr_0']
    for i in range(len(raw_murder_nums)):
        if int(raw_murder_nums[i][:4]) != int(year):
            df.set_value(i, raw_murder_nums[i], np.nan)
            
df.head()

HBox(children=(IntProgress(value=0, max=21264), HTML(value='')))

//anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:13: FutureWarning: set_value is deprecated and will be removed in a future release. Please use .at[] or .iat[] accessors instead
  del sys.path[0]

CPU times: user 4.13 s, sys: 86.6 ms, total: 4.21 s
Wall time: 4.58 s

,Unnamed: 0,Unnamed: 0.1,ID,State,City,agyaddr,xobsyr_0,Illicit_Days5,Illicit_Cens5,female_cd,nonwhite_cd,unemplmt_cd,prsatx_cd,gvsg_cd,CWSg_0_cd,srprobg_cd,dssg_0_cd,epsg_0_cd,adhdg_0_cd,cdsg_0_cd,cjsig_0_cd,lrig_0_cd,srig_0_cd,SESg_0_cd,r4ag_0_cd,nonillicit_flag,primsev_cd_1,primsev_cd_2,primsev_cd_3,primsev_cd_4,primsev_cd_5,primsev_cd_6,B2a_0g,SUDSy_0,SDSl_0,Address,lat,lng,state_name,county_FIPS,block_FIPS,2002_raw_murder_num,2003_raw_murder_num,2004_raw_murder_num,2005_raw_murder_num,2006_raw_murder_num,2007_raw_murder_num,2008_raw_murder_num,2009_raw_murder_num,2010_raw_murder_num,2011_raw_murder_num,2012_raw_murder_num
0,0,1,857,OH,Cleveland,1276 West Third St. #400,2005,365,0,0,0,0,0,2,0,0,1,1,1,1,0,1,2,0,1,1,1,0,0,0,0,0,0,0,0,"1276 West Third St. #400, Cleveland, OH",41.419286,-81.701695,Ohio,39035.0,3.903511e+14,NaN,73.0,79.0,109.0,77.0,90.0,55.0,83.0,81.0,74.0,84.0
1,1,2,929,OH,Cleveland,1276 West Third St. #400,2006,354,0,0,0,0,0,1,0,1,0,1,0,1,1,0,1,0,2,1,1,0,0,0,0,0,0,3,2,"1276 West Third St. #400, Cleveland, OH",41.419286,-81.701695,Ohio,39035.0,3.903511e+14,80.0,NaN,79.0,109.0,77.0,90.0,55.0,83.0,81.0,74.0,84.0
2,2,3,951,OH,Cleveland,1276 West Third St. #400,2006,365,0,0,0,0,0,0,0,1,0,0,0,0,1,0,1,0,2,1,0,0,1,0,0,0,0,2,1,"1276 West Third St. #400, Cleveland, OH",41.419286,-81.701695,Ohio,39035.0,3.903511e+14,80.0,73.0,NaN,109.0,77.0,90.0,55.0,83.0,81.0,74.0,84.0
3,3,4,1032,OH,Cleveland,1276 West Third St. #400,2006,365,0,0,0,0,0,2,0,1,1,1,1,1,0,2,1,0,2,1,0,0,1,0,0,0,0,2,1,"1276 West Third St. #400, Cleveland, OH",41.419286,-81.701695,Ohio,39035.0,3.903511e+14,80.0,73.0,79.0,NaN,77.0,90.0,55.0,83.0,81.0,74.0,84.0
4,4,5,1039,OH,Cleveland,1276 West Third St. #400,2004,365,0,0,0,0,0,0,0,0,1,0,0,1,1,2,1,0,2,0,0,1,0,0,0,0,0,0,0,"1276 West Third St. #400, Cleveland, OH",41.419286,-81.701695,Ohio,39035.0,3.903511e+14,80.0,73.0,79.0,109.0,NaN,90.0,55.0,83.0,81.0,74.0,84.0

In [12]:
# condense murder_num feature across years into one column

df['murder_num'] = np.nan

for i in range(len(raw_murder_nums)):
    df['murder_num'] = df['murder_num'].fillna(df[raw_murder_nums[i]])

df.drop(columns=raw_murder_nums, inplace=True) # drop extra rows after condensing murder_num feature
df.head()

,Unnamed: 0,Unnamed: 0.1,ID,State,City,agyaddr,xobsyr_0,Illicit_Days5,Illicit_Cens5,female_cd,nonwhite_cd,unemplmt_cd,prsatx_cd,gvsg_cd,CWSg_0_cd,srprobg_cd,dssg_0_cd,epsg_0_cd,adhdg_0_cd,cdsg_0_cd,cjsig_0_cd,lrig_0_cd,srig_0_cd,SESg_0_cd,r4ag_0_cd,nonillicit_flag,primsev_cd_1,primsev_cd_2,primsev_cd_3,primsev_cd_4,primsev_cd_5,primsev_cd_6,B2a_0g,SUDSy_0,SDSl_0,Address,lat,lng,state_name,county_FIPS,block_FIPS,murder_num
0,0,1,857,OH,Cleveland,1276 West Third St. #400,2005,365,0,0,0,0,0,2,0,0,1,1,1,1,0,1,2,0,1,1,1,0,0,0,0,0,0,0,0,"1276 West Third St. #400, Cleveland, OH",41.419286,-81.701695,Ohio,39035.0,3.903511e+14,73.0
1,1,2,929,OH,Cleveland,1276 West Third St. #400,2006,354,0,0,0,0,0,1,0,1,0,1,0,1,1,0,1,0,2,1,1,0,0,0,0,0,0,3,2,"1276 West Third St. #400, Cleveland, OH",41.419286,-81.701695,Ohio,39035.0,3.903511e+14,80.0
2,2,3,951,OH,Cleveland,1276 West Third St. #400,2006,365,0,0,0,0,0,0,0,1,0,0,0,0,1,0,1,0,2,1,0,0,1,0,0,0,0,2,1,"1276 West Third St. #400, Cleveland, OH",41.419286,-81.701695,Ohio,39035.0,3.903511e+14,80.0
3,3,4,1032,OH,Cleveland,1276 West Third St. #400,2006,365,0,0,0,0,0,2,0,1,1,1,1,1,0,2,1,0,2,1,0,0,1,0,0,0,0,2,1,"1276 West Third St. #400, Cleveland, OH",41.419286,-81.701695,Ohio,39035.0,3.903511e+14,80.0
4,4,5,1039,OH,Cleveland,1276 West Third St. #400,2004,365,0,0,0,0,0,0,0,0,1,0,0,1,1,2,1,0,2,0,0,1,0,0,0,0,0,0,0,"1276 West Third St. #400, Cleveland, OH",41.419286,-81.701695,Ohio,39035.0,3.903511e+14,80.0

In [13]:
low = df['murder_num'].min()
high = df['murder_num'].max()
third = (high - low) / 3

df['murder_numg'] = pd.cut(df['murder_num'], [low,low+third,low+2*third,high], labels=[0, 1, 2])
df.drop(columns='murder_num', inplace=True)
df.head()

,Unnamed: 0,Unnamed: 0.1,ID,State,City,agyaddr,xobsyr_0,Illicit_Days5,Illicit_Cens5,female_cd,nonwhite_cd,unemplmt_cd,prsatx_cd,gvsg_cd,CWSg_0_cd,srprobg_cd,dssg_0_cd,epsg_0_cd,adhdg_0_cd,cdsg_0_cd,cjsig_0_cd,lrig_0_cd,srig_0_cd,SESg_0_cd,r4ag_0_cd,nonillicit_flag,primsev_cd_1,primsev_cd_2,primsev_cd_3,primsev_cd_4,primsev_cd_5,primsev_cd_6,B2a_0g,SUDSy_0,SDSl_0,Address,lat,lng,state_name,county_FIPS,block_FIPS,murder_numg
0,0,1,857,OH,Cleveland,1276 West Third St. #400,2005,365,0,0,0,0,0,2,0,0,1,1,1,1,0,1,2,0,1,1,1,0,0,0,0,0,0,0,0,"1276 West Third St. #400, Cleveland, OH",41.419286,-81.701695,Ohio,39035.0,3.903511e+14,0
1,1,2,929,OH,Cleveland,1276 West Third St. #400,2006,354,0,0,0,0,0,1,0,1,0,1,0,1,1,0,1,0,2,1,1,0,0,0,0,0,0,3,2,"1276 West Third St. #400, Cleveland, OH",41.419286,-81.701695,Ohio,39035.0,3.903511e+14,0
2,2,3,951,OH,Cleveland,1276 West Third St. #400,2006,365,0,0,0,0,0,0,0,1,0,0,0,0,1,0,1,0,2,1,0,0,1,0,0,0,0,2,1,"1276 West Third St. #400, Cleveland, OH",41.419286,-81.701695,Ohio,39035.0,3.903511e+14,0
3,3,4,1032,OH,Cleveland,1276 West Third St. #400,2006,365,0,0,0,0,0,2,0,1,1,1,1,1,0,2,1,0,2,1,0,0,1,0,0,0,0,2,1,"1276 West Third St. #400, Cleveland, OH",41.419286,-81.701695,Ohio,39035.0,3.903511e+14,0
4,4,5,1039,OH,Cleveland,1276 West Third St. #400,2004,365,0,0,0,0,0,0,0,0,1,0,0,1,1,2,1,0,2,0,0,1,0,0,0,0,0,0,0,"1276 West Third St. #400, Cleveland, OH",41.419286,-81.701695,Ohio,39035.0,3.903511e+14,0

In [14]:
df.shape[0] - df['murder_numg'].isna().sum() # see how many rows have murder data

12922

Add Concentrated Disadvantage Data

In [15]:
# start with raw numbers, end with FIPS code and concentrated disadvantage feature
def calculate_concentrated_disadvantage(filename):
    df_census = pd.read_csv(filename, encoding = "ISO-8859-1")
    
    cols_to_use = ['SE_A01001_001','SE_A01001_002','SE_A01001_003','SE_A01001_004','SE_A01001_005','SE_A10008_001',
                   'SE_A10008_006','SE_A10008_009','SE_A17005_001','SE_A17005_003','SE_A10014_001','SE_A10014_002',
                   'SE_A13003A_001','SE_A13003A_002','SE_A13003B_001','SE_A13003B_002','SE_A13003C_001',
                   'SE_A13003C_002','Geo_FIPS']
    df_census = df_census[cols_to_use]

    # calculate percentage under 18
    age_cols = ['SE_A01001_002', 'SE_A01001_003', 'SE_A01001_004', 'SE_A01001_005']
    df_census['%_U18'] = df_census[age_cols].sum(axis=1) / df_census['SE_A01001_001']
    age_cols.append('SE_A01001_001')
    df_census.drop(columns=age_cols, inplace=True)

    # calculate percentage female households
    female_householder_cols = ['SE_A10008_006', 'SE_A10008_009']
    df_census['%_female_household'] = df_census[female_householder_cols].sum(axis=1) / df_census['SE_A10008_001']
    female_householder_cols.append('SE_A10008_001')
    df_census.drop(columns=female_householder_cols, inplace=True)

    # calculate percentage unemployed
    df_census['%_unemployed'] = df_census['SE_A17005_003'] / df_census['SE_A17005_001']
    df_census.drop(columns=['SE_A17005_003', 'SE_A17005_001'], inplace=True)

    # calculate percentage households with public assistance income 
    df_census['%_public_assistance'] = df_census['SE_A10014_002'] / df_census['SE_A10014_001']
    df_census.drop(columns=['SE_A10014_001', 'SE_A10014_002'], inplace=True)

    # calculate percentage living in poverty
    population_cols = ['SE_A13003A_001', 'SE_A13003B_001', 'SE_A13003C_001']
    poverty_cols = ['SE_A13003A_002', 'SE_A13003B_002', 'SE_A13003C_002']
    df_census['%_poverty'] = df_census[poverty_cols].sum(axis=1) / df_census[population_cols].sum(axis=1)
    df_census.drop(columns=(population_cols + poverty_cols), inplace=True)

    """# calculate z-scores of 5 census variables
    cols_to_z_score = ['%_U18', '%_female_household', '%_unemployed', '%_public_assistance', '%_poverty']
    for col in cols_to_z_score:
        df_census[col] = (df_census[col] - df_census[col].mean())/df_census[col].std(ddof=0)

    # average z-scored census variables to get concentrated disadvantage
    df_census['concentrated_disadvantage'] = df_census[cols_to_z_score].mean(axis=1)
    
    cuttoff = df_census['concentrated_disadvantage'].quantile(.75)
    df_census['hcd'] = np.where(df_census['concentrated_disadvantage']>=cuttoff, 1, 0)
    df_census.drop(columns='concentrated_disadvantage', inplace=True)"""
    
    df_census['xobsyr_0'] = year
    return df_census

In [16]:
%%time

from functools import reduce

years = [2012, 2011, 2010, 2009, 2008, 2007, 2006] # NOTE: must be in descending order
frames = []

# collect at county level
for year in years:
    df_census = calculate_concentrated_disadvantage('census_data/county/ACS1yr' + str(year) + 'Census.csv')
    df_census['gran'] = 0
    frames.append(df_census)

# collect at census_tract level
for year in years[:-3]:
    df_census = calculate_concentrated_disadvantage('census_data/census_tract/ACS5yr' + str(year) + 'Census.csv')
    df_census['gran'] = 1
    frames.append(df_census)    
    
hcd = pd.concat(frames)
hcd.head()

CPU times: user 2.79 s, sys: 503 ms, total: 3.29 s
Wall time: 3.32 s

,Geo_FIPS,%_U18,%_female_household,%_unemployed,%_public_assistance,%_poverty,xobsyr_0,gran
0,1003,0.222837,0.263844,0.087921,0.010490,0.140557,2012,0
1,1015,0.224347,0.310551,0.153805,0.023790,0.221665,2012,0
2,1043,0.223309,0.294499,0.075186,0.024197,0.197444,2012,0
3,1049,0.253700,0.238181,0.081434,0.017791,0.132595,2012,0
4,1051,0.230475,0.280535,0.061826,0.012887,0.129935,2012,0

In [17]:
# group raw variables 

raw_census_vars = ['%_U18', '%_female_household', '%_unemployed', '%_public_assistance', '%_poverty']

for feat in raw_census_vars:
    low = hcd[feat].min()
    high = hcd[feat].max()
    quarter = (high - low) / 4

    new_feat = feat + 'g'
    
    # separate into bottom 25%, middle 50%, and upper 25%
    hcd[new_feat] = pd.cut(hcd[feat], [low,low+quarter,low+3*quarter,high], labels=[0, 1, 2])
    hcd.drop(columns=feat, inplace=True)

hcd.tail()

,Geo_FIPS,xobsyr_0,gran,%_U18g,%_female_householdg,%_unemployedg,%_public_assistanceg,%_povertyg
66317,72153750501,2009,1,1,1,0,0,1
66318,72153750502,2009,1,0,1,1,0,1
66319,72153750503,2009,1,1,1,0,0,1
66320,72153750601,2009,1,1,1,0,0,1
66321,72153750602,2009,1,0,1,1,0,1

In [18]:
hcd['Geo_FIPS'] = hcd['Geo_FIPS'].astype(str)
hcd.dtypes

Geo_FIPS                  object
xobsyr_0                   int64
gran                       int64
%_U18g                  category
%_female_householdg     category
%_unemployedg           category
%_public_assistanceg    category
%_povertyg              category
dtype: object

In [19]:
# pull out unique county/year combinations
fips_df = df[['block_FIPS', 'county_FIPS', 'xobsyr_0', 'Address']]
fips_df = fips_df.drop_duplicates(subset=['Address', 'xobsyr_0'])
fips_df['block_FIPS'] = fips_df['block_FIPS'].astype(str).str[:-2] # 54.099e15 -> 540990051001055.0 -> 540990051001055
fips_df['county_FIPS'] = fips_df['county_FIPS'].astype(str).str[:-2] # 54099.0 -> 54099
fips_df.head()

,block_FIPS,county_FIPS,xobsyr_0,Address
0,390351059002009,39035,2005,"1276 West Third St. #400, Cleveland, OH"
1,390351059002009,39035,2006,"1276 West Third St. #400, Cleveland, OH"
4,390351059002009,39035,2004,"1276 West Third St. #400, Cleveland, OH"
5,191030003012027,19103,2005,"100 Oakdale Campus - M319, Iowa City, IA"
6,191030003012027,19103,2006,"100 Oakdale Campus - M319, Iowa City, IA"

In [20]:
fips_df.shape

(596, 4)

In [21]:
from tqdm.notebook import tqdm # used to show progress bar

for i,row in tqdm(fips_df.iterrows(), total=fips_df.shape[0]):
    if len(row['block_FIPS'].strip()) != 15:
        fips_df.set_value(i, 'block_FIPS', '0' + row['block_FIPS'].strip())
    if len(row['county_FIPS'].strip()) != 5:
        fips_df.set_value(i, 'county_FIPS', '0' + row['county_FIPS'].strip())
        
fips_df = fips_df.astype(str)
fips_df.head()

HBox(children=(IntProgress(value=0, max=596), HTML(value='')))

//anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:5: FutureWarning: set_value is deprecated and will be removed in a future release. Please use .at[] or .iat[] accessors instead
  """
//anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:7: FutureWarning: set_value is deprecated and will be removed in a future release. Please use .at[] or .iat[] accessors instead
  import sys

,block_FIPS,county_FIPS,xobsyr_0,Address
0,390351059002009,39035,2005,"1276 West Third St. #400, Cleveland, OH"
1,390351059002009,39035,2006,"1276 West Third St. #400, Cleveland, OH"
4,390351059002009,39035,2004,"1276 West Third St. #400, Cleveland, OH"
5,191030003012027,19103,2005,"100 Oakdale Campus - M319, Iowa City, IA"
6,191030003012027,19103,2006,"100 Oakdale Campus - M319, Iowa City, IA"

In [22]:
fips_df = fips_df[fips_df.xobsyr_0 >= '2006']

fips_df['gran'] = np.nan
fips_df['%_U18g'] = np.nan
fips_df['%_female_householdg'] = np.nan
fips_df['%_unemployedg'] = np.nan
fips_df['%_public_assistanceg'] = np.nan
fips_df['%_povertyg'] = np.nan

fips_df.shape

(474, 10)

In [23]:
# merge with patient location data

print('Merging at census tract level...')
for i,row in tqdm(fips_df.iterrows(), total=fips_df.shape[0]):
    try:
        block_FIPS = row['block_FIPS']
        xobsyr_0 = row['xobsyr_0']
        hcd_df = hcd[hcd.xobsyr_0 == int(xobsyr_0)]
        hcd_df = hcd_df[hcd_df.gran == 1]
        for j,r in hcd_df.iterrows():
            #print(r['xobsyr_0'], '=>', xobsyr_0, block_FIPS, '=>', r['Geo_FIPS'])
            if block_FIPS.startswith(r['Geo_FIPS']): 
                #print('here!!')
                fips_df.set_value(i, 'gran', 1)
                fips_df.set_value(i, '%_U18g', r['%_U18g'])
                fips_df.set_value(i, '%_female_householdg', r['%_female_householdg'])
                fips_df.set_value(i, '%_unemployedg', r['%_unemployedg'])
                fips_df.set_value(i, '%_public_assistanceg', r['%_public_assistanceg'])
                fips_df.set_value(i, '%_povertyg', r['%_povertyg'])
                break
    except Exception as e:
        print('Error with line ' + i, e)
            
fips_df.head()

Merging at census tract level...

HBox(children=(IntProgress(value=0, max=474), HTML(value='')))

//anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:14: FutureWarning: set_value is deprecated and will be removed in a future release. Please use .at[] or .iat[] accessors instead

//anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:15: FutureWarning: set_value is deprecated and will be removed in a future release. Please use .at[] or .iat[] accessors instead
  from ipykernel import kernelapp as app
//anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:16: FutureWarning: set_value is deprecated and will be removed in a future release. Please use .at[] or .iat[] accessors instead
  app.launch_new_instance()
//anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:17: FutureWarning: set_value is deprecated and will be removed in a future release. Please use .at[] or .iat[] accessors instead
//anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:18: FutureWarning: set_value is deprecated and will be removed in a future release. Please use .at[] or .iat[] accessors instead
//anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:19: FutureWarning: set_value is deprecated and will be removed in a future release. Please use .at[] or .iat[] accessors instead

,block_FIPS,county_FIPS,xobsyr_0,Address,gran,%_U18g,%_female_householdg,%_unemployedg,%_public_assistanceg,%_povertyg
1,390351059002009,39035,2006,"1276 West Third St. #400, Cleveland, OH",NaN,NaN,NaN,NaN,NaN,NaN
6,191030003012027,19103,2006,"100 Oakdale Campus - M319, Iowa City, IA",NaN,NaN,NaN,NaN,NaN,NaN
18,211110083002011,21111,2006,"1220 Bardstown Rd, Louisville, KY",NaN,NaN,NaN,NaN,NaN,NaN
21,040190007003001,04019,2006,"3130 E Broadway Blvd, Tucson, AZ",NaN,NaN,NaN,NaN,NaN,NaN
27,481410043124008,48141,2008,"1111 Barranca Dr., Suite 800, El Paso, TX",NaN,NaN,NaN,NaN,NaN,NaN

In [24]:
fips_df.shape[0] - fips_df['gran'].isna().sum() # see how many rows have census data

196

In [25]:
print('Merging remaining with county level data...')
for i,row in tqdm(fips_df.iterrows(), total=fips_df.shape[0]):
    try:
        if pd.isna(row).sum() > 0: # if not filled by block_FIPS
            print('here!', row['gran'])
            county_FIPS = row['county_FIPS']
            xobsyr_0 = row['xobsyr_0']
            hcd_df = hcd[hcd.xobsyr_0 == int(xobsyr_0)]
            hcd_df = hcd_df[hcd_df.gran == 0]
            for j,r in hcd_df.iterrows():
                #print(county_FIPS, '=>', r['Geo_FIPS'])
                try:
                    if int(r['Geo_FIPS']) == int(county_FIPS): 
                        #print('here!!', r['Geo_FIPS'], '==', county_FIPS)
                        fips_df.set_value(i, 'gran', 0)
                        fips_df.set_value(i, '%_U18g', r['%_U18g'])
                        fips_df.set_value(i, '%_female_householdg', r['%_female_householdg'])
                        fips_df.set_value(i, '%_unemployedg', r['%_unemployedg'])
                        fips_df.set_value(i, '%_public_assistanceg', r['%_public_assistanceg'])
                        fips_df.set_value(i, '%_povertyg', r['%_povertyg'])
                        break
                except Exception as e:
                    print('Error comparing', r['Geo_FIPS'], 'with', county_FIPS)
    except Exception as e:
        print('Error with line ' + i, e)

Merging remaining with county level data...

HBox(children=(IntProgress(value=0, max=474), HTML(value='')))

here! nan
here! nan
here! nan
here! nan
here! nan

//anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:15: FutureWarning: set_value is deprecated and will be removed in a future release. Please use .at[] or .iat[] accessors instead
  from ipykernel import kernelapp as app
//anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:16: FutureWarning: set_value is deprecated and will be removed in a future release. Please use .at[] or .iat[] accessors instead
  app.launch_new_instance()
//anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:17: FutureWarning: set_value is deprecated and will be removed in a future release. Please use .at[] or .iat[] accessors instead
//anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:18: FutureWarning: set_value is deprecated and will be removed in a future release. Please use .at[] or .iat[] accessors instead
//anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:19: FutureWarning: set_value is deprecated and will be removed in a future release. Please use .at[] or .iat[] accessors instead
//anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:20: FutureWarning: set_value is deprecated and will be removed in a future release. Please use .at[] or .iat[] accessors instead

here! nan
here! nan
here! nan
here! nan
here! nan
here! nan
here! nan
here! nan
here! nan
here! nan
here! nan
here! nan
here! nan
here! nan
here! nan
here! nan
here! nan
here! nan
here! nan
here! nan
here! 1.0
here! 1.0
here! 1.0
here! nan
here! nan
here! nan
here! nan
here! nan
here! nan
here! nan
here! nan
here! nan
here! nan
here! nan
here! nan
here! 1.0
here! 1.0
here! 1.0
here! nan
here! nan
here! nan
here! nan
here! 1.0
here! nan
here! nan
here! nan
here! nan
here! nan
here! 1.0
here! nan
here! nan
here! nan
here! nan
here! nan
here! nan
here! 1.0
here! nan
here! nan
here! nan
here! nan
here! nan
here! nan
here! nan
here! nan
here! nan
here! nan
here! nan
here! nan
here! nan
here! nan
here! nan
here! nan
here! nan
here! nan
here! nan
here! nan
here! nan
here! nan
here! nan
here! nan
here! nan
here! nan
here! nan
here! nan
here! nan
here! nan
here! nan
here! nan
here! nan
here! nan
here! nan
here! 1.0
here! 1.0
here! 1.0
here! nan
here! nan
here! nan
here! nan
here! nan
here! nan
here! nan
here! nan
here! nan
here! nan
here! nan
here! nan
here! nan
here! nan
here! nan
here! nan
here! nan
here! nan
here! nan
here! nan
here! nan
here! nan
here! nan
here! nan
here! nan
here! nan
here! nan
here! nan
here! nan
here! nan
here! nan
here! nan
here! 1.0
here! nan
here! nan
here! nan
here! nan
here! 1.0
here! nan
here! 1.0
here! nan
here! 1.0
here! nan
here! nan
here! nan
here! nan
here! nan
here! nan
here! nan
here! nan
here! nan
here! nan
here! nan
here! nan
here! nan
here! nan
here! nan
here! nan
here! nan
here! nan
here! nan
here! nan
here! nan
here! nan
here! nan
here! nan
here! nan
here! nan
here! nan
here! nan
here! nan
here! nan
here! 1.0
here! nan
here! nan
here! nan
here! nan
here! nan
here! nan
here! nan
here! nan
here! nan
here! nan
here! nan
here! nan
here! nan
here! nan
here! nan
here! nan
here! nan
here! nan
here! nan
here! nan
here! 1.0
here! nan
here! nan
here! nan
here! nan
here! nan
here! nan
here! nan
here! nan
here! nan
here! nan
here! nan
here! nan
here! nan
here! nan
here! nan
here! 1.0
here! 1.0
here! 1.0
here! 1.0
here! nan
here! nan
here! nan
here! nan
here! nan
here! nan
here! 1.0
here! nan
here! nan
here! nan
here! 1.0
here! nan
here! nan
here! 1.0
here! nan
here! nan
here! nan
here! nan
here! nan
here! nan
here! nan
here! nan
here! nan
here! nan
here! nan
here! nan
here! nan
here! nan
here! nan
here! nan
here! 1.0
here! 1.0
here! nan
here! nan
here! 1.0
here! nan
here! nan
here! nan
Error comparing 1003 with 0n
Error comparing 1015 with 0n
Error comparing 1043 with 0n
Error comparing 1049 with 0n
Error comparing 1051 with 0n
Error comparing 1055 with 0n
Error comparing 1069 with 0n
Error comparing 1073 with 0n
Error comparing 1077 with 0n
Error comparing 1081 with 0n
Error comparing 1083 with 0n
Error comparing 1089 with 0n
Error comparing 1095 with 0n
Error comparing 1097 with 0n
Error comparing 1101 with 0n
Error comparing 1103 with 0n
Error comparing 1115 with 0n
Error comparing 1117 with 0n
Error comparing 1121 with 0n
Error comparing 1125 with 0n
Error comparing 1127 with 0n
Error comparing 2020 with 0n
Error comparing 2090 with 0n
Error comparing 2170 with 0n
Error comparing 4001 with 0n
Error comparing 4003 with 0n
Error comparing 4005 with 0n
Error comparing 4013 with 0n
Error comparing 4015 with 0n
Error comparing 4017 with 0n
Error comparing 4019 with 0n
Error comparing 4021 with 0n
Error comparing 4025 with 0n
Error comparing 4027 with 0n
Error comparing 5007 with 0n
Error comparing 5031 with 0n
Error comparing 5045 with 0n
Error comparing 5051 with 0n
Error comparing 5069 with 0n
Error comparing 5085 with 0n
Error comparing 5119 with 0n
Error comparing 5125 with 0n
Error comparing 5131 with 0n
Error comparing 5143 with 0n
Error comparing 5145 with 0n
Error comparing 6001 with 0n
Error comparing 6007 with 0n
Error comparing 6013 with 0n
Error comparing 6017 with 0n
Error comparing 6019 with 0n
Error comparing 6023 with 0n
Error comparing 6025 with 0n
Error comparing 6029 with 0n
Error comparing 6031 with 0n
Error comparing 6033 with 0n
Error comparing 6037 with 0n
Error comparing 6039 with 0n
Error comparing 6041 with 0n
Error comparing 6045 with 0n
Error comparing 6047 with 0n
Error comparing 6053 with 0n
Error comparing 6055 with 0n
Error comparing 6057 with 0n
Error comparing 6059 with 0n
Error comparing 6061 with 0n
Error comparing 6065 with 0n
Error comparing 6067 with 0n
Error comparing 6071 with 0n
Error comparing 6073 with 0n
Error comparing 6075 with 0n
Error comparing 6077 with 0n
Error comparing 6079 with 0n
Error comparing 6081 with 0n
Error comparing 6083 with 0n
Error comparing 6085 with 0n
Error comparing 6087 with 0n
Error comparing 6089 with 0n
Error comparing 6095 with 0n
Error comparing 6097 with 0n
Error comparing 6099 with 0n
Error comparing 6101 with 0n
Error comparing 6107 with 0n
Error comparing 6111 with 0n
Error comparing 6113 with 0n
Error comparing 6115 with 0n
Error comparing 8001 with 0n
Error comparing 8005 with 0n
Error comparing 8013 with 0n
Error comparing 8031 with 0n
Error comparing 8035 with 0n
Error comparing 8041 with 0n
Error comparing 8059 with 0n
Error comparing 8069 with 0n
Error comparing 8077 with 0n
Error comparing 8101 with 0n
Error comparing 8123 with 0n
Error comparing 9001 with 0n
Error comparing 9003 with 0n
Error comparing 9005 with 0n
Error comparing 9007 with 0n
Error comparing 9009 with 0n
Error comparing 9011 with 0n
Error comparing 9013 with 0n
Error comparing 9015 with 0n
Error comparing 10001 with 0n
Error comparing 10003 with 0n
Error comparing 10005 with 0n
Error comparing 11001 with 0n
Error comparing 12001 with 0n
Error comparing 12005 with 0n
Error comparing 12009 with 0n
Error comparing 12011 with 0n
Error comparing 12015 with 0n
Error comparing 12017 with 0n
Error comparing 12019 with 0n
Error comparing 12021 with 0n
Error comparing 12023 with 0n
Error comparing 12031 with 0n
Error comparing 12033 with 0n
Error comparing 12035 with 0n
Error comparing 12053 with 0n
Error comparing 12055 with 0n
Error comparing 12057 with 0n
Error comparing 12061 with 0n
Error comparing 12069 with 0n
Error comparing 12071 with 0n
Error comparing 12073 with 0n
Error comparing 12081 with 0n
Error comparing 12083 with 0n
Error comparing 12085 with 0n
Error comparing 12086 with 0n
Error comparing 12087 with 0n
Error comparing 12089 with 0n
Error comparing 12091 with 0n
Error comparing 12095 with 0n
Error comparing 12097 with 0n
Error comparing 12099 with 0n
Error comparing 12101 with 0n
Error comparing 12103 with 0n
Error comparing 12105 with 0n
Error comparing 12107 with 0n
Error comparing 12109 with 0n
Error comparing 12111 with 0n
Error comparing 12113 with 0n
Error comparing 12115 with 0n
Error comparing 12117 with 0n
Error comparing 12119 with 0n
Error comparing 12127 with 0n
Error comparing 13013 with 0n
Error comparing 13015 with 0n
Error comparing 13021 with 0n
Error comparing 13031 with 0n
Error comparing 13045 with 0n
Error comparing 13051 with 0n
Error comparing 13057 with 0n
Error comparing 13059 with 0n
Error comparing 13063 with 0n
Error comparing 13067 with 0n
Error comparing 13073 with 0n
Error comparing 13077 with 0n
Error comparing 13089 with 0n
Error comparing 13095 with 0n
Error comparing 13097 with 0n
Error comparing 13113 with 0n
Error comparing 13115 with 0n
Error comparing 13117 with 0n
Error comparing 13121 with 0n
Error comparing 13127 with 0n
Error comparing 13135 with 0n
Error comparing 13139 with 0n
Error comparing 13151 with 0n
Error comparing 13153 with 0n
Error comparing 13179 with 0n
Error comparing 13185 with 0n
Error comparing 13215 with 0n
Error comparing 13217 with 0n
Error comparing 13223 with 0n
Error comparing 13245 with 0n
Error comparing 13247 with 0n
Error comparing 13285 with 0n
Error comparing 13295 with 0n
Error comparing 13297 with 0n
Error comparing 13313 with 0n
Error comparing 15001 with 0n
Error comparing 15003 with 0n
Error comparing 15007 with 0n
Error comparing 15009 with 0n
Error comparing 16001 with 0n
Error comparing 16005 with 0n
Error comparing 16019 with 0n
Error comparing 16027 with 0n
Error comparing 16055 with 0n
Error comparing 16083 with 0n
Error comparing 17001 with 0n
Error comparing 17019 with 0n
Error comparing 17031 with 0n
Error comparing 17037 with 0n
Error comparing 17043 with 0n
Error comparing 17089 with 0n
Error comparing 17091 with 0n
Error comparing 17093 with 0n
Error comparing 17097 with 0n
Error comparing 17099 with 0n
Error comparing 17111 with 0n
Error comparing 17113 with 0n
Error comparing 17115 with 0n
Error comparing 17119 with 0n
Error comparing 17143 with 0n
Error comparing 17161 with 0n
Error comparing 17163 with 0n
Error comparing 17167 with 0n
Error comparing 17179 with 0n
Error comparing 17183 with 0n
Error comparing 17197 with 0n
Error comparing 17199 with 0n
Error comparing 17201 with 0n
Error comparing 18003 with 0n
Error comparing 18005 with 0n
Error comparing 18019 with 0n
Error comparing 18035 with 0n
Error comparing 18039 with 0n
Error comparing 18043 with 0n
Error comparing 18053 with 0n
Error comparing 18057 with 0n
Error comparing 18059 with 0n
Error comparing 18063 with 0n
Error comparing 18067 with 0n
Error comparing 18081 with 0n
Error comparing 18085 with 0n
Error comparing 18089 with 0n
Error comparing 18091 with 0n
Error comparing 18095 with 0n
Error comparing 18097 with 0n
Error comparing 18105 with 0n
Error comparing 18109 with 0n
Error comparing 18127 with 0n
Error comparing 18141 with 0n
Error comparing 18157 with 0n
Error comparing 18163 with 0n
Error comparing 18167 with 0n
Error comparing 18177 with 0n
Error comparing 19013 with 0n
Error comparing 19049 with 0n
Error comparing 19061 with 0n
Error comparing 19103 with 0n
Error comparing 19113 with 0n
Error comparing 19153 with 0n
Error comparing 19155 with 0n
Error comparing 19163 with 0n
Error comparing 19169 with 0n
Error comparing 19193 with 0n
Error comparing 20015 with 0n
Error comparing 20045 with 0n
Error comparing 20091 with 0n
Error comparing 20103 with 0n
Error comparing 20161 with 0n
Error comparing 20173 with 0n
Error comparing 20177 with 0n
Error comparing 20209 with 0n
Error comparing 21015 with 0n
Error comparing 21029 with 0n
Error comparing 21037 with 0n
Error comparing 21047 with 0n
Error comparing 21059 with 0n
Error comparing 21067 with 0n
Error comparing 21093 with 0n
Error comparing 21111 with 0n
Error comparing 21117 with 0n
Error comparing 21145 with 0n
Error comparing 21151 with 0n
Error comparing 21195 with 0n
Error comparing 21227 with 0n
Error comparing 22005 with 0n
Error comparing 22015 with 0n
Error comparing 22017 with 0n
Error comparing 22019 with 0n
Error comparing 22033 with 0n
Error comparing 22045 with 0n
Error comparing 22051 with 0n
Error comparing 22055 with 0n
Error comparing 22057 with 0n
Error comparing 22063 with 0n
Error comparing 22071 with 0n
Error comparing 22073 with 0n
Error comparing 22079 with 0n
Error comparing 22097 with 0n
Error comparing 22103 with 0n
Error comparing 22105 with 0n
Error comparing 22109 with 0n
Error comparing 23001 with 0n
Error comparing 23003 with 0n
Error comparing 23005 with 0n
Error comparing 23011 with 0n
Error comparing 23019 with 0n
Error comparing 23031 with 0n
Error comparing 24001 with 0n
Error comparing 24003 with 0n
Error comparing 24005 with 0n
Error comparing 24009 with 0n
Error comparing 24013 with 0n
Error comparing 24015 with 0n
Error comparing 24017 with 0n
Error comparing 24021 with 0n
Error comparing 24025 with 0n
Error comparing 24027 with 0n
Error comparing 24031 with 0n
Error comparing 24033 with 0n
Error comparing 24037 with 0n
Error comparing 24043 with 0n
Error comparing 24045 with 0n
Error comparing 24510 with 0n
Error comparing 25001 with 0n
Error comparing 25003 with 0n
Error comparing 25005 with 0n
Error comparing 25009 with 0n
Error comparing 25011 with 0n
Error comparing 25013 with 0n
Error comparing 25015 with 0n
Error comparing 25017 with 0n
Error comparing 25021 with 0n
Error comparing 25023 with 0n
Error comparing 25025 with 0n
Error comparing 25027 with 0n
Error comparing 26005 with 0n
Error comparing 26017 with 0n
Error comparing 26021 with 0n
Error comparing 26025 with 0n
Error comparing 26037 with 0n
Error comparing 26045 with 0n
Error comparing 26049 with 0n
Error comparing 26055 with 0n
Error comparing 26065 with 0n
Error comparing 26073 with 0n
Error comparing 26075 with 0n
Error comparing 26077 with 0n
Error comparing 26081 with 0n
Error comparing 26087 with 0n
Error comparing 26091 with 0n
Error comparing 26093 with 0n
Error comparing 26099 with 0n
Error comparing 26103 with 0n
Error comparing 26111 with 0n
Error comparing 26115 with 0n
Error comparing 26121 with 0n
Error comparing 26125 with 0n
Error comparing 26139 with 0n
Error comparing 26145 with 0n
Error comparing 26147 with 0n
Error comparing 26155 with 0n
Error comparing 26159 with 0n
Error comparing 26161 with 0n
Error comparing 26163 with 0n
Error comparing 27003 with 0n
Error comparing 27019 with 0n
Error comparing 27037 with 0n
Error comparing 27053 with 0n
Error comparing 27109 with 0n
Error comparing 27123 with 0n
Error comparing 27137 with 0n
Error comparing 27139 with 0n
Error comparing 27141 with 0n
Error comparing 27145 with 0n
Error comparing 27163 with 0n
Error comparing 27171 with 0n
Error comparing 28033 with 0n
Error comparing 28035 with 0n
Error comparing 28047 with 0n
Error comparing 28049 with 0n
Error comparing 28059 with 0n
Error comparing 28067 with 0n
Error comparing 28075 with 0n

Error comparing 28081 with 0n
Error comparing 28089 with 0n
Error comparing 28121 with 0n
Error comparing 29019 with 0n
Error comparing 29021 with 0n
Error comparing 29031 with 0n
Error comparing 29037 with 0n
Error comparing 29043 with 0n
Error comparing 29047 with 0n
Error comparing 29051 with 0n
Error comparing 29071 with 0n
Error comparing 29077 with 0n
Error comparing 29095 with 0n
Error comparing 29097 with 0n
Error comparing 29099 with 0n
Error comparing 29165 with 0n
Error comparing 29183 with 0n
Error comparing 29187 with 0n
Error comparing 29189 with 0n
Error comparing 29510 with 0n
Error comparing 30013 with 0n
Error comparing 30029 with 0n
Error comparing 30031 with 0n
Error comparing 30063 with 0n
Error comparing 30111 with 0n
Error comparing 31055 with 0n
Error comparing 31109 with 0n
Error comparing 31153 with 0n
Error comparing 32003 with 0n
Error comparing 32031 with 0n
Error comparing 33005 with 0n
Error comparing 33009 with 0n
Error comparing 33011 with 0n
Error comparing 33013 with 0n
Error comparing 33015 with 0n
Error comparing 33017 with 0n
Error comparing 34001 with 0n
Error comparing 34003 with 0n
Error comparing 34005 with 0n
Error comparing 34007 with 0n
Error comparing 34009 with 0n
Error comparing 34011 with 0n
Error comparing 34013 with 0n
Error comparing 34015 with 0n
Error comparing 34017 with 0n
Error comparing 34019 with 0n
Error comparing 34021 with 0n
Error comparing 34023 with 0n
Error comparing 34025 with 0n
Error comparing 34027 with 0n
Error comparing 34029 with 0n
Error comparing 34031 with 0n
Error comparing 34033 with 0n
Error comparing 34035 with 0n
Error comparing 34037 with 0n
Error comparing 34039 with 0n
Error comparing 34041 with 0n
Error comparing 35001 with 0n
Error comparing 35005 with 0n
Error comparing 35013 with 0n
Error comparing 35025 with 0n
Error comparing 35031 with 0n
Error comparing 35035 with 0n
Error comparing 35043 with 0n
Error comparing 35045 with 0n
Error comparing 35049 with 0n
Error comparing 35061 with 0n
Error comparing 36001 with 0n
Error comparing 36005 with 0n
Error comparing 36007 with 0n
Error comparing 36009 with 0n
Error comparing 36011 with 0n
Error comparing 36013 with 0n
Error comparing 36015 with 0n
Error comparing 36019 with 0n
Error comparing 36027 with 0n
Error comparing 36029 with 0n
Error comparing 36045 with 0n
Error comparing 36047 with 0n
Error comparing 36051 with 0n
Error comparing 36053 with 0n
Error comparing 36055 with 0n
Error comparing 36059 with 0n
Error comparing 36061 with 0n
Error comparing 36063 with 0n
Error comparing 36065 with 0n
Error comparing 36067 with 0n
Error comparing 36069 with 0n
Error comparing 36071 with 0n
Error comparing 36075 with 0n
Error comparing 36079 with 0n
Error comparing 36081 with 0n
Error comparing 36083 with 0n
Error comparing 36085 with 0n
Error comparing 36087 with 0n
Error comparing 36089 with 0n
Error comparing 36091 with 0n
Error comparing 36093 with 0n
Error comparing 36101 with 0n
Error comparing 36103 with 0n
Error comparing 36105 with 0n
Error comparing 36109 with 0n
Error comparing 36111 with 0n
Error comparing 36113 with 0n
Error comparing 36117 with 0n
Error comparing 36119 with 0n
Error comparing 37001 with 0n
Error comparing 37019 with 0n
Error comparing 37021 with 0n
Error comparing 37023 with 0n
Error comparing 37025 with 0n
Error comparing 37027 with 0n
Error comparing 37031 with 0n
Error comparing 37035 with 0n
Error comparing 37045 with 0n
Error comparing 37049 with 0n
Error comparing 37051 with 0n
Error comparing 37057 with 0n
Error comparing 37063 with 0n
Error comparing 37067 with 0n
Error comparing 37071 with 0n
Error comparing 37081 with 0n
Error comparing 37085 with 0n
Error comparing 37089 with 0n
Error comparing 37097 with 0n
Error comparing 37101 with 0n
Error comparing 37109 with 0n
Error comparing 37119 with 0n
Error comparing 37125 with 0n
Error comparing 37127 with 0n
Error comparing 37129 with 0n
Error comparing 37133 with 0n
Error comparing 37135 with 0n
Error comparing 37147 with 0n
Error comparing 37151 with 0n
Error comparing 37155 with 0n
Error comparing 37157 with 0n
Error comparing 37159 with 0n
Error comparing 37161 with 0n
Error comparing 37171 with 0n
Error comparing 37179 with 0n
Error comparing 37183 with 0n
Error comparing 37191 with 0n
Error comparing 37193 with 0n
Error comparing 37195 with 0n
Error comparing 38015 with 0n
Error comparing 38017 with 0n
Error comparing 38035 with 0n
Error comparing 39003 with 0n
Error comparing 39007 with 0n
Error comparing 39013 with 0n
Error comparing 39017 with 0n
Error comparing 39023 with 0n
Error comparing 39025 with 0n
Error comparing 39029 with 0n
Error comparing 39035 with 0n
Error comparing 39041 with 0n
Error comparing 39043 with 0n
Error comparing 39045 with 0n
Error comparing 39049 with 0n
Error comparing 39055 with 0n
Error comparing 39057 with 0n
Error comparing 39061 with 0n
Error comparing 39063 with 0n
Error comparing 39081 with 0n
Error comparing 39085 with 0n
Error comparing 39089 with 0n
Error comparing 39093 with 0n
Error comparing 39095 with 0n
Error comparing 39099 with 0n
Error comparing 39101 with 0n
Error comparing 39103 with 0n
Error comparing 39109 with 0n
Error comparing 39113 with 0n
Error comparing 39119 with 0n
Error comparing 39133 with 0n
Error comparing 39139 with 0n
Error comparing 39141 with 0n
Error comparing 39145 with 0n
Error comparing 39151 with 0n
Error comparing 39153 with 0n
Error comparing 39155 with 0n
Error comparing 39157 with 0n
Error comparing 39165 with 0n
Error comparing 39169 with 0n
Error comparing 39173 with 0n
Error comparing 40017 with 0n
Error comparing 40027 with 0n
Error comparing 40031 with 0n
Error comparing 40037 with 0n
Error comparing 40101 with 0n
Error comparing 40109 with 0n
Error comparing 40119 with 0n
Error comparing 40125 with 0n
Error comparing 40131 with 0n
Error comparing 40143 with 0n
Error comparing 40145 with 0n
Error comparing 41003 with 0n
Error comparing 41005 with 0n
Error comparing 41017 with 0n
Error comparing 41019 with 0n
Error comparing 41029 with 0n
Error comparing 41033 with 0n
Error comparing 41035 with 0n
Error comparing 41039 with 0n
Error comparing 41043 with 0n
Error comparing 41047 with 0n
Error comparing 41051 with 0n
Error comparing 41053 with 0n
Error comparing 41059 with 0n
Error comparing 41067 with 0n
Error comparing 41071 with 0n
Error comparing 42001 with 0n
Error comparing 42003 with 0n
Error comparing 42005 with 0n
Error comparing 42007 with 0n
Error comparing 42011 with 0n
Error comparing 42013 with 0n
Error comparing 42017 with 0n
Error comparing 42019 with 0n
Error comparing 42021 with 0n
Error comparing 42025 with 0n
Error comparing 42027 with 0n
Error comparing 42029 with 0n
Error comparing 42033 with 0n
Error comparing 42037 with 0n
Error comparing 42039 with 0n
Error comparing 42041 with 0n
Error comparing 42043 with 0n
Error comparing 42045 with 0n
Error comparing 42049 with 0n
Error comparing 42051 with 0n
Error comparing 42055 with 0n
Error comparing 42063 with 0n
Error comparing 42069 with 0n
Error comparing 42071 with 0n
Error comparing 42073 with 0n
Error comparing 42075 with 0n
Error comparing 42077 with 0n
Error comparing 42079 with 0n
Error comparing 42081 with 0n
Error comparing 42085 with 0n
Error comparing 42089 with 0n
Error comparing 42091 with 0n
Error comparing 42095 with 0n
Error comparing 42097 with 0n
Error comparing 42101 with 0n
Error comparing 42107 with 0n
Error comparing 42111 with 0n
Error comparing 42125 with 0n
Error comparing 42129 with 0n
Error comparing 42133 with 0n
Error comparing 44003 with 0n
Error comparing 44005 with 0n
Error comparing 44007 with 0n
Error comparing 44009 with 0n
Error comparing 45003 with 0n
Error comparing 45007 with 0n
Error comparing 45013 with 0n
Error comparing 45015 with 0n
Error comparing 45019 with 0n
Error comparing 45031 with 0n
Error comparing 45035 with 0n
Error comparing 45041 with 0n
Error comparing 45045 with 0n
Error comparing 45047 with 0n
Error comparing 45051 with 0n
Error comparing 45057 with 0n
Error comparing 45059 with 0n
Error comparing 45063 with 0n
Error comparing 45073 with 0n
Error comparing 45075 with 0n
Error comparing 45077 with 0n
Error comparing 45079 with 0n
Error comparing 45083 with 0n
Error comparing 45085 with 0n
Error comparing 45091 with 0n
Error comparing 46099 with 0n
Error comparing 46103 with 0n
Error comparing 47001 with 0n
Error comparing 47009 with 0n
Error comparing 47011 with 0n
Error comparing 47037 with 0n

Error comparing 47059 with 0n
Error comparing 47065 with 0n
Error comparing 47093 with 0n
Error comparing 47113 with 0n
Error comparing 47119 with 0n
Error comparing 47125 with 0n
Error comparing 47141 with 0n
Error comparing 47147 with 0n
Error comparing 47149 with 0n
Error comparing 47155 with 0n
Error comparing 47157 with 0n
Error comparing 47163 with 0n
Error comparing 47165 with 0n
Error comparing 47179 with 0n
Error comparing 47187 with 0n
Error comparing 47189 with 0n
Error comparing 48005 with 0n
Error comparing 48021 with 0n
Error comparing 48027 with 0n
Error comparing 48029 with 0n
Error comparing 48037 with 0n
Error comparing 48039 with 0n
Error comparing 48041 with 0n
Error comparing 48061 with 0n
Error comparing 48085 with 0n
Error comparing 48091 with 0n
Error comparing 48099 with 0n
Error comparing 48113 with 0n
Error comparing 48121 with 0n
Error comparing 48135 with 0n
Error comparing 48139 with 0n
Error comparing 48141 with 0n
Error comparing 48157 with 0n
Error comparing 48167 with 0n
Error comparing 48181 with 0n
Error comparing 48183 with 0n
Error comparing 48187 with 0n
Error comparing 48201 with 0n
Error comparing 48203 with 0n
Error comparing 48209 with 0n
Error comparing 48213 with 0n
Error comparing 48215 with 0n
Error comparing 48231 with 0n
Error comparing 48245 with 0n
Error comparing 48251 with 0n
Error comparing 48257 with 0n
Error comparing 48291 with 0n
Error comparing 48303 with 0n
Error comparing 48309 with 0n
Error comparing 48329 with 0n
Error comparing 48339 with 0n
Error comparing 48347 with 0n
Error comparing 48355 with 0n
Error comparing 48361 with 0n
Error comparing 48367 with 0n
Error comparing 48375 with 0n
Error comparing 48381 with 0n
Error comparing 48397 with 0n
Error comparing 48409 with 0n
Error comparing 48423 with 0n
Error comparing 48439 with 0n
Error comparing 48441 with 0n
Error comparing 48451 with 0n
Error comparing 48453 with 0n
Error comparing 48469 with 0n
Error comparing 48471 with 0n
Error comparing 48479 with 0n
Error comparing 48485 with 0n
Error comparing 48491 with 0n
Error comparing 49005 with 0n
Error comparing 49011 with 0n
Error comparing 49035 with 0n
Error comparing 49049 with 0n
Error comparing 49053 with 0n
Error comparing 49057 with 0n
Error comparing 50007 with 0n
Error comparing 51003 with 0n
Error comparing 51013 with 0n
Error comparing 51015 with 0n
Error comparing 51019 with 0n
Error comparing 51041 with 0n
Error comparing 51059 with 0n
Error comparing 51061 with 0n
Error comparing 51069 with 0n
Error comparing 51085 with 0n
Error comparing 51087 with 0n
Error comparing 51095 with 0n
Error comparing 51107 with 0n
Error comparing 51121 with 0n
Error comparing 51153 with 0n
Error comparing 51161 with 0n
Error comparing 51165 with 0n
Error comparing 51177 with 0n
Error comparing 51179 with 0n
Error comparing 51199 with 0n
Error comparing 51510 with 0n
Error comparing 51550 with 0n
Error comparing 51650 with 0n
Error comparing 51680 with 0n
Error comparing 51700 with 0n
Error comparing 51710 with 0n
Error comparing 51740 with 0n
Error comparing 51760 with 0n
Error comparing 51770 with 0n
Error comparing 51800 with 0n
Error comparing 51810 with 0n
Error comparing 53005 with 0n
Error comparing 53007 with 0n
Error comparing 53009 with 0n
Error comparing 53011 with 0n
Error comparing 53015 with 0n
Error comparing 53021 with 0n
Error comparing 53025 with 0n
Error comparing 53027 with 0n
Error comparing 53029 with 0n
Error comparing 53033 with 0n
Error comparing 53035 with 0n
Error comparing 53041 with 0n
Error comparing 53053 with 0n
Error comparing 53057 with 0n
Error comparing 53061 with 0n
Error comparing 53063 with 0n
Error comparing 53067 with 0n
Error comparing 53073 with 0n
Error comparing 53077 with 0n
Error comparing 54003 with 0n
Error comparing 54011 with 0n
Error comparing 54033 with 0n
Error comparing 54039 with 0n
Error comparing 54061 with 0n
Error comparing 54081 with 0n
Error comparing 54107 with 0n
Error comparing 55009 with 0n
Error comparing 55025 with 0n
Error comparing 55027 with 0n
Error comparing 55035 with 0n
Error comparing 55039 with 0n
Error comparing 55055 with 0n
Error comparing 55059 with 0n
Error comparing 55063 with 0n
Error comparing 55071 with 0n
Error comparing 55073 with 0n
Error comparing 55079 with 0n
Error comparing 55087 with 0n
Error comparing 55089 with 0n
Error comparing 55097 with 0n
Error comparing 55101 with 0n
Error comparing 55105 with 0n
Error comparing 55109 with 0n
Error comparing 55117 with 0n
Error comparing 55127 with 0n
Error comparing 55131 with 0n
Error comparing 55133 with 0n
Error comparing 55139 with 0n
Error comparing 55141 with 0n
Error comparing 56021 with 0n
Error comparing 56025 with 0n
Error comparing 72013 with 0n
Error comparing 72021 with 0n
Error comparing 72025 with 0n
Error comparing 72031 with 0n
Error comparing 72061 with 0n
Error comparing 72097 with 0n
Error comparing 72113 with 0n
Error comparing 72127 with 0n
Error comparing 72135 with 0n
Error comparing 72137 with 0n
Error comparing 72139 with 0n
here! nan
here! nan
here! nan
here! nan
here! 1.0
here! nan
here! nan
Error comparing 1003 with 0n
Error comparing 1015 with 0n
Error comparing 1043 with 0n
Error comparing 1049 with 0n
Error comparing 1051 with 0n
Error comparing 1055 with 0n
Error comparing 1069 with 0n
Error comparing 1073 with 0n
Error comparing 1077 with 0n
Error comparing 1081 with 0n
Error comparing 1083 with 0n
Error comparing 1089 with 0n
Error comparing 1095 with 0n
Error comparing 1097 with 0n
Error comparing 1101 with 0n
Error comparing 1103 with 0n
Error comparing 1115 with 0n
Error comparing 1117 with 0n
Error comparing 1121 with 0n
Error comparing 1125 with 0n
Error comparing 1127 with 0n
Error comparing 2020 with 0n
Error comparing 2090 with 0n
Error comparing 2170 with 0n
Error comparing 4001 with 0n
Error comparing 4003 with 0n
Error comparing 4005 with 0n
Error comparing 4013 with 0n
Error comparing 4015 with 0n
Error comparing 4017 with 0n
Error comparing 4019 with 0n
Error comparing 4021 with 0n
Error comparing 4025 with 0n
Error comparing 4027 with 0n
Error comparing 5007 with 0n
Error comparing 5031 with 0n
Error comparing 5045 with 0n
Error comparing 5051 with 0n
Error comparing 5069 with 0n
Error comparing 5085 with 0n
Error comparing 5119 with 0n
Error comparing 5125 with 0n
Error comparing 5131 with 0n
Error comparing 5143 with 0n
Error comparing 5145 with 0n
Error comparing 6001 with 0n
Error comparing 6007 with 0n
Error comparing 6013 with 0n
Error comparing 6017 with 0n
Error comparing 6019 with 0n
Error comparing 6023 with 0n
Error comparing 6025 with 0n
Error comparing 6029 with 0n
Error comparing 6031 with 0n
Error comparing 6033 with 0n
Error comparing 6037 with 0n
Error comparing 6039 with 0n
Error comparing 6041 with 0n
Error comparing 6045 with 0n
Error comparing 6047 with 0n
Error comparing 6053 with 0n
Error comparing 6055 with 0n
Error comparing 6057 with 0n
Error comparing 6059 with 0n
Error comparing 6061 with 0n
Error comparing 6065 with 0n
Error comparing 6067 with 0n
Error comparing 6071 with 0n
Error comparing 6073 with 0n
Error comparing 6075 with 0n
Error comparing 6077 with 0n
Error comparing 6079 with 0n
Error comparing 6081 with 0n
Error comparing 6083 with 0n
Error comparing 6085 with 0n
Error comparing 6087 with 0n
Error comparing 6089 with 0n
Error comparing 6095 with 0n
Error comparing 6097 with 0n
Error comparing 6099 with 0n
Error comparing 6101 with 0n
Error comparing 6107 with 0n
Error comparing 6111 with 0n
Error comparing 6113 with 0n
Error comparing 6115 with 0n
Error comparing 8001 with 0n
Error comparing 8005 with 0n
Error comparing 8013 with 0n
Error comparing 8031 with 0n
Error comparing 8035 with 0n
Error comparing 8041 with 0n
Error comparing 8059 with 0n
Error comparing 8069 with 0n
Error comparing 8077 with 0n
Error comparing 8101 with 0n
Error comparing 8123 with 0n
Error comparing 9001 with 0n
Error comparing 9003 with 0n
Error comparing 9005 with 0n
Error comparing 9007 with 0n
Error comparing 9009 with 0n
Error comparing 9011 with 0n
Error comparing 9013 with 0n
Error comparing 9015 with 0n
Error comparing 10001 with 0n
Error comparing 10003 with 0n
Error comparing 10005 with 0n
Error comparing 11001 with 0n
Error comparing 12001 with 0n
Error comparing 12005 with 0n
Error comparing 12009 with 0n
Error comparing 12011 with 0n
Error comparing 12015 with 0n
Error comparing 12017 with 0n
Error comparing 12019 with 0n
Error comparing 12021 with 0n
Error comparing 12023 with 0n
Error comparing 12031 with 0n
Error comparing 12033 with 0n
Error comparing 12035 with 0n
Error comparing 12053 with 0n
Error comparing 12055 with 0n
Error comparing 12057 with 0n
Error comparing 12061 with 0n
Error comparing 12069 with 0n
Error comparing 12071 with 0n
Error comparing 12073 with 0n
Error comparing 12081 with 0n
Error comparing 12083 with 0n
Error comparing 12085 with 0n
Error comparing 12086 with 0n
Error comparing 12087 with 0n
Error comparing 12089 with 0n
Error comparing 12091 with 0n
Error comparing 12095 with 0n
Error comparing 12097 with 0n
Error comparing 12099 with 0n
Error comparing 12101 with 0n
Error comparing 12103 with 0n
Error comparing 12105 with 0n
Error comparing 12107 with 0n
Error comparing 12109 with 0n
Error comparing 12111 with 0n
Error comparing 12113 with 0n
Error comparing 12115 with 0n
Error comparing 12117 with 0n
Error comparing 12119 with 0n
Error comparing 12127 with 0n
Error comparing 13013 with 0n
Error comparing 13015 with 0n
Error comparing 13021 with 0n
Error comparing 13031 with 0n
Error comparing 13045 with 0n
Error comparing 13047 with 0n
Error comparing 13051 with 0n
Error comparing 13057 with 0n
Error comparing 13059 with 0n
Error comparing 13063 with 0n
Error comparing 13067 with 0n
Error comparing 13073 with 0n
Error comparing 13077 with 0n
Error comparing 13089 with 0n
Error comparing 13095 with 0n
Error comparing 13097 with 0n
Error comparing 13113 with 0n
Error comparing 13115 with 0n
Error comparing 13117 with 0n
Error comparing 13121 with 0n
Error comparing 13127 with 0n
Error comparing 13135 with 0n
Error comparing 13139 with 0n
Error comparing 13151 with 0n
Error comparing 13153 with 0n
Error comparing 13179 with 0n
Error comparing 13185 with 0n
Error comparing 13215 with 0n
Error comparing 13217 with 0n
Error comparing 13223 with 0n
Error comparing 13245 with 0n
Error comparing 13247 with 0n
Error comparing 13285 with 0n
Error comparing 13295 with 0n
Error comparing 13297 with 0n
Error comparing 13313 with 0n
Error comparing 15001 with 0n
Error comparing 15003 with 0n
Error comparing 15007 with 0n
Error comparing 15009 with 0n
Error comparing 16001 with 0n
Error comparing 16005 with 0n
Error comparing 16019 with 0n
Error comparing 16027 with 0n
Error comparing 16055 with 0n
Error comparing 16083 with 0n
Error comparing 17001 with 0n
Error comparing 17019 with 0n
Error comparing 17031 with 0n
Error comparing 17037 with 0n
Error comparing 17043 with 0n
Error comparing 17089 with 0n
Error comparing 17091 with 0n
Error comparing 17093 with 0n
Error comparing 17097 with 0n
Error comparing 17099 with 0n
Error comparing 17111 with 0n
Error comparing 17113 with 0n
Error comparing 17115 with 0n
Error comparing 17119 with 0n
Error comparing 17143 with 0n
Error comparing 17161 with 0n
Error comparing 17163 with 0n
Error comparing 17167 with 0n
Error comparing 17179 with 0n
Error comparing 17183 with 0n
Error comparing 17197 with 0n
Error comparing 17199 with 0n
Error comparing 17201 with 0n
Error comparing 18003 with 0n
Error comparing 18005 with 0n
Error comparing 18019 with 0n
Error comparing 18035 with 0n
Error comparing 18039 with 0n
Error comparing 18043 with 0n
Error comparing 18053 with 0n
Error comparing 18057 with 0n
Error comparing 18059 with 0n
Error comparing 18063 with 0n
Error comparing 18067 with 0n
Error comparing 18081 with 0n
Error comparing 18085 with 0n
Error comparing 18089 with 0n
Error comparing 18091 with 0n
Error comparing 18095 with 0n
Error comparing 18097 with 0n
Error comparing 18105 with 0n
Error comparing 18109 with 0n
Error comparing 18127 with 0n
Error comparing 18141 with 0n
Error comparing 18157 with 0n
Error comparing 18163 with 0n
Error comparing 18167 with 0n
Error comparing 18177 with 0n
Error comparing 19013 with 0n
Error comparing 19049 with 0n
Error comparing 19061 with 0n
Error comparing 19103 with 0n
Error comparing 19113 with 0n
Error comparing 19153 with 0n
Error comparing 19155 with 0n
Error comparing 19163 with 0n
Error comparing 19169 with 0n
Error comparing 19193 with 0n
Error comparing 20015 with 0n
Error comparing 20045 with 0n
Error comparing 20091 with 0n
Error comparing 20103 with 0n
Error comparing 20161 with 0n
Error comparing 20173 with 0n
Error comparing 20177 with 0n
Error comparing 20209 with 0n
Error comparing 21015 with 0n
Error comparing 21029 with 0n
Error comparing 21037 with 0n
Error comparing 21047 with 0n
Error comparing 21059 with 0n
Error comparing 21067 with 0n
Error comparing 21093 with 0n
Error comparing 21111 with 0n
Error comparing 21117 with 0n
Error comparing 21145 with 0n
Error comparing 21151 with 0n
Error comparing 21195 with 0n
Error comparing 21227 with 0n
Error comparing 22005 with 0n
Error comparing 22015 with 0n
Error comparing 22017 with 0n
Error comparing 22019 with 0n
Error comparing 22033 with 0n
Error comparing 22045 with 0n
Error comparing 22051 with 0n
Error comparing 22055 with 0n
Error comparing 22057 with 0n
Error comparing 22063 with 0n
Error comparing 22071 with 0n
Error comparing 22073 with 0n
Error comparing 22079 with 0n
Error comparing 22097 with 0n
Error comparing 22103 with 0n
Error comparing 22105 with 0n
Error comparing 22109 with 0n
Error comparing 23001 with 0n
Error comparing 23003 with 0n
Error comparing 23005 with 0n
Error comparing 23011 with 0n
Error comparing 23019 with 0n
Error comparing 23031 with 0n
Error comparing 24001 with 0n
Error comparing 24003 with 0n
Error comparing 24005 with 0n
Error comparing 24009 with 0n
Error comparing 24013 with 0n
Error comparing 24015 with 0n
Error comparing 24017 with 0n
Error comparing 24021 with 0n
Error comparing 24025 with 0n
Error comparing 24027 with 0n
Error comparing 24031 with 0n
Error comparing 24033 with 0n
Error comparing 24037 with 0n
Error comparing 24043 with 0n
Error comparing 24045 with 0n
Error comparing 24510 with 0n
Error comparing 25001 with 0n
Error comparing 25003 with 0n
Error comparing 25005 with 0n
Error comparing 25009 with 0n
Error comparing 25011 with 0n
Error comparing 25013 with 0n
Error comparing 25015 with 0n
Error comparing 25017 with 0n
Error comparing 25021 with 0n
Error comparing 25023 with 0n
Error comparing 25025 with 0n
Error comparing 25027 with 0n
Error comparing 26005 with 0n
Error comparing 26017 with 0n
Error comparing 26021 with 0n

Error comparing 26025 with 0n
Error comparing 26037 with 0n
Error comparing 26045 with 0n
Error comparing 26049 with 0n
Error comparing 26055 with 0n
Error comparing 26065 with 0n
Error comparing 26073 with 0n
Error comparing 26075 with 0n
Error comparing 26077 with 0n
Error comparing 26081 with 0n
Error comparing 26087 with 0n
Error comparing 26091 with 0n
Error comparing 26093 with 0n
Error comparing 26099 with 0n
Error comparing 26103 with 0n
Error comparing 26111 with 0n
Error comparing 26115 with 0n
Error comparing 26121 with 0n
Error comparing 26125 with 0n
Error comparing 26139 with 0n
Error comparing 26145 with 0n
Error comparing 26147 with 0n
Error comparing 26155 with 0n
Error comparing 26159 with 0n
Error comparing 26161 with 0n
Error comparing 26163 with 0n
Error comparing 27003 with 0n
Error comparing 27013 with 0n
Error comparing 27019 with 0n
Error comparing 27037 with 0n
Error comparing 27053 with 0n
Error comparing 27109 with 0n
Error comparing 27123 with 0n
Error comparing 27137 with 0n
Error comparing 27139 with 0n
Error comparing 27141 with 0n
Error comparing 27145 with 0n
Error comparing 27163 with 0n
Error comparing 27171 with 0n
Error comparing 28033 with 0n
Error comparing 28035 with 0n
Error comparing 28047 with 0n
Error comparing 28049 with 0n
Error comparing 28059 with 0n
Error comparing 28067 with 0n
Error comparing 28075 with 0n
Error comparing 28081 with 0n
Error comparing 28089 with 0n
Error comparing 28121 with 0n
Error comparing 29019 with 0n
Error comparing 29021 with 0n
Error comparing 29031 with 0n
Error comparing 29037 with 0n
Error comparing 29043 with 0n
Error comparing 29047 with 0n
Error comparing 29051 with 0n
Error comparing 29071 with 0n
Error comparing 29077 with 0n
Error comparing 29095 with 0n
Error comparing 29097 with 0n
Error comparing 29099 with 0n
Error comparing 29165 with 0n
Error comparing 29183 with 0n
Error comparing 29187 with 0n
Error comparing 29189 with 0n
Error comparing 29510 with 0n
Error comparing 30013 with 0n
Error comparing 30029 with 0n
Error comparing 30031 with 0n
Error comparing 30063 with 0n
Error comparing 30111 with 0n
Error comparing 31055 with 0n
Error comparing 31109 with 0n
Error comparing 31153 with 0n
Error comparing 32003 with 0n
Error comparing 32031 with 0n
Error comparing 33005 with 0n
Error comparing 33009 with 0n
Error comparing 33011 with 0n
Error comparing 33013 with 0n
Error comparing 33015 with 0n
Error comparing 33017 with 0n
Error comparing 34001 with 0n
Error comparing 34003 with 0n
Error comparing 34005 with 0n
Error comparing 34007 with 0n
Error comparing 34009 with 0n
Error comparing 34011 with 0n
Error comparing 34013 with 0n
Error comparing 34015 with 0n
Error comparing 34017 with 0n
Error comparing 34019 with 0n
Error comparing 34021 with 0n
Error comparing 34023 with 0n
Error comparing 34025 with 0n
Error comparing 34027 with 0n
Error comparing 34029 with 0n
Error comparing 34031 with 0n
Error comparing 34033 with 0n
Error comparing 34035 with 0n
Error comparing 34037 with 0n
Error comparing 34039 with 0n
Error comparing 34041 with 0n
Error comparing 35001 with 0n
Error comparing 35005 with 0n
Error comparing 35013 with 0n
Error comparing 35025 with 0n
Error comparing 35031 with 0n
Error comparing 35035 with 0n
Error comparing 35043 with 0n
Error comparing 35045 with 0n
Error comparing 35049 with 0n
Error comparing 35061 with 0n
Error comparing 36001 with 0n
Error comparing 36005 with 0n
Error comparing 36007 with 0n
Error comparing 36009 with 0n
Error comparing 36011 with 0n
Error comparing 36013 with 0n
Error comparing 36015 with 0n
Error comparing 36019 with 0n
Error comparing 36027 with 0n
Error comparing 36029 with 0n
Error comparing 36045 with 0n
Error comparing 36047 with 0n
Error comparing 36051 with 0n
Error comparing 36053 with 0n
Error comparing 36055 with 0n
Error comparing 36059 with 0n
Error comparing 36061 with 0n
Error comparing 36063 with 0n
Error comparing 36065 with 0n
Error comparing 36067 with 0n
Error comparing 36069 with 0n
Error comparing 36071 with 0n
Error comparing 36075 with 0n
Error comparing 36079 with 0n
Error comparing 36081 with 0n
Error comparing 36083 with 0n
Error comparing 36085 with 0n
Error comparing 36087 with 0n
Error comparing 36089 with 0n
Error comparing 36091 with 0n
Error comparing 36093 with 0n
Error comparing 36101 with 0n
Error comparing 36103 with 0n
Error comparing 36105 with 0n
Error comparing 36109 with 0n
Error comparing 36111 with 0n
Error comparing 36113 with 0n
Error comparing 36117 with 0n
Error comparing 36119 with 0n
Error comparing 37001 with 0n
Error comparing 37019 with 0n
Error comparing 37021 with 0n
Error comparing 37023 with 0n
Error comparing 37025 with 0n
Error comparing 37027 with 0n
Error comparing 37031 with 0n
Error comparing 37035 with 0n
Error comparing 37037 with 0n
Error comparing 37045 with 0n
Error comparing 37049 with 0n
Error comparing 37051 with 0n
Error comparing 37057 with 0n
Error comparing 37063 with 0n
Error comparing 37067 with 0n
Error comparing 37071 with 0n
Error comparing 37081 with 0n
Error comparing 37085 with 0n
Error comparing 37089 with 0n
Error comparing 37097 with 0n
Error comparing 37101 with 0n
Error comparing 37109 with 0n
Error comparing 37119 with 0n
Error comparing 37125 with 0n
Error comparing 37127 with 0n
Error comparing 37129 with 0n
Error comparing 37133 with 0n
Error comparing 37135 with 0n
Error comparing 37147 with 0n
Error comparing 37151 with 0n
Error comparing 37155 with 0n
Error comparing 37157 with 0n
Error comparing 37159 with 0n
Error comparing 37161 with 0n
Error comparing 37171 with 0n
Error comparing 37179 with 0n
Error comparing 37183 with 0n
Error comparing 37191 with 0n
Error comparing 37193 with 0n
Error comparing 37195 with 0n
Error comparing 38015 with 0n
Error comparing 38017 with 0n
Error comparing 38035 with 0n
Error comparing 39003 with 0n
Error comparing 39007 with 0n
Error comparing 39013 with 0n
Error comparing 39017 with 0n
Error comparing 39023 with 0n
Error comparing 39025 with 0n
Error comparing 39029 with 0n
Error comparing 39035 with 0n
Error comparing 39041 with 0n
Error comparing 39043 with 0n
Error comparing 39045 with 0n
Error comparing 39049 with 0n
Error comparing 39055 with 0n
Error comparing 39057 with 0n
Error comparing 39061 with 0n
Error comparing 39063 with 0n
Error comparing 39081 with 0n
Error comparing 39085 with 0n
Error comparing 39089 with 0n
Error comparing 39093 with 0n
Error comparing 39095 with 0n
Error comparing 39099 with 0n
Error comparing 39101 with 0n
Error comparing 39103 with 0n
Error comparing 39109 with 0n
Error comparing 39113 with 0n
Error comparing 39119 with 0n
Error comparing 39133 with 0n
Error comparing 39139 with 0n
Error comparing 39141 with 0n
Error comparing 39145 with 0n
Error comparing 39151 with 0n
Error comparing 39153 with 0n
Error comparing 39155 with 0n
Error comparing 39157 with 0n
Error comparing 39165 with 0n
Error comparing 39169 with 0n
Error comparing 39173 with 0n
Error comparing 40017 with 0n
Error comparing 40027 with 0n
Error comparing 40031 with 0n
Error comparing 40037 with 0n
Error comparing 40101 with 0n
Error comparing 40109 with 0n
Error comparing 40119 with 0n
Error comparing 40125 with 0n
Error comparing 40131 with 0n
Error comparing 40143 with 0n
Error comparing 40145 with 0n
Error comparing 41003 with 0n
Error comparing 41005 with 0n
Error comparing 41017 with 0n
Error comparing 41019 with 0n
Error comparing 41029 with 0n
Error comparing 41033 with 0n
Error comparing 41035 with 0n
Error comparing 41039 with 0n
Error comparing 41043 with 0n
Error comparing 41047 with 0n
Error comparing 41051 with 0n
Error comparing 41053 with 0n
Error comparing 41059 with 0n
Error comparing 41067 with 0n
Error comparing 41071 with 0n
Error comparing 42001 with 0n
Error comparing 42003 with 0n
Error comparing 42005 with 0n
Error comparing 42007 with 0n
Error comparing 42011 with 0n
Error comparing 42013 with 0n
Error comparing 42017 with 0n
Error comparing 42019 with 0n
Error comparing 42021 with 0n
Error comparing 42025 with 0n
Error comparing 42027 with 0n
Error comparing 42029 with 0n
Error comparing 42033 with 0n
Error comparing 42037 with 0n
Error comparing 42039 with 0n
Error comparing 42041 with 0n
Error comparing 42043 with 0n
Error comparing 42045 with 0n
Error comparing 42049 with 0n
Error comparing 42051 with 0n
Error comparing 42055 with 0n
Error comparing 42063 with 0n
Error comparing 42069 with 0n
Error comparing 42071 with 0n
Error comparing 42073 with 0n
Error comparing 42075 with 0n
Error comparing 42077 with 0n
Error comparing 42079 with 0n
Error comparing 42081 with 0n
Error comparing 42085 with 0n
Error comparing 42089 with 0n
Error comparing 42091 with 0n
Error comparing 42095 with 0n
Error comparing 42097 with 0n
Error comparing 42101 with 0n
Error comparing 42107 with 0n
Error comparing 42111 with 0n
Error comparing 42125 with 0n
Error comparing 42129 with 0n
Error comparing 42133 with 0n
Error comparing 44003 with 0n
Error comparing 44005 with 0n
Error comparing 44007 with 0n
Error comparing 44009 with 0n
Error comparing 45003 with 0n
Error comparing 45007 with 0n
Error comparing 45013 with 0n
Error comparing 45015 with 0n
Error comparing 45019 with 0n
Error comparing 45031 with 0n
Error comparing 45035 with 0n
Error comparing 45041 with 0n
Error comparing 45045 with 0n
Error comparing 45047 with 0n
Error comparing 45051 with 0n
Error comparing 45057 with 0n
Error comparing 45059 with 0n
Error comparing 45063 with 0n
Error comparing 45073 with 0n
Error comparing 45075 with 0n
Error comparing 45077 with 0n
Error comparing 45079 with 0n
Error comparing 45083 with 0n
Error comparing 45085 with 0n
Error comparing 45091 with 0n
Error comparing 46099 with 0n
Error comparing 46103 with 0n
Error comparing 47001 with 0n
Error comparing 47009 with 0n
Error comparing 47011 with 0n
Error comparing 47037 with 0n
Error comparing 47059 with 0n
Error comparing 47065 with 0n
Error comparing 47093 with 0n
Error comparing 47113 with 0n
Error comparing 47119 with 0n
Error comparing 47125 with 0n
Error comparing 47141 with 0n
Error comparing 47147 with 0n
Error comparing 47149 with 0n
Error comparing 47155 with 0n
Error comparing 47157 with 0n
Error comparing 47163 with 0n
Error comparing 47165 with 0n
Error comparing 47179 with 0n
Error comparing 47187 with 0n
Error comparing 47189 with 0n
Error comparing 48005 with 0n
Error comparing 48021 with 0n
Error comparing 48027 with 0n
Error comparing 48029 with 0n
Error comparing 48037 with 0n
Error comparing 48039 with 0n
Error comparing 48041 with 0n
Error comparing 48061 with 0n
Error comparing 48085 with 0n
Error comparing 48091 with 0n
Error comparing 48099 with 0n
Error comparing 48113 with 0n
Error comparing 48121 with 0n
Error comparing 48135 with 0n
Error comparing 48139 with 0n
Error comparing 48141 with 0n
Error comparing 48157 with 0n
Error comparing 48167 with 0n
Error comparing 48181 with 0n
Error comparing 48183 with 0n
Error comparing 48187 with 0n
Error comparing 48201 with 0n
Error comparing 48203 with 0n
Error comparing 48209 with 0n
Error comparing 48213 with 0n
Error comparing 48215 with 0n
Error comparing 48231 with 0n
Error comparing 48245 with 0n
Error comparing 48251 with 0n
Error comparing 48257 with 0n
Error comparing 48291 with 0n
Error comparing 48303 with 0n
Error comparing 48309 with 0n
Error comparing 48329 with 0n
Error comparing 48339 with 0n
Error comparing 48347 with 0n
Error comparing 48355 with 0n
Error comparing 48361 with 0n
Error comparing 48367 with 0n
Error comparing 48375 with 0n
Error comparing 48381 with 0n
Error comparing 48397 with 0n
Error comparing 48409 with 0n
Error comparing 48423 with 0n
Error comparing 48439 with 0n
Error comparing 48441 with 0n
Error comparing 48451 with 0n
Error comparing 48453 with 0n
Error comparing 48469 with 0n
Error comparing 48471 with 0n

Error comparing 48479 with 0n
Error comparing 48485 with 0n
Error comparing 48491 with 0n
Error comparing 49005 with 0n
Error comparing 49011 with 0n
Error comparing 49035 with 0n
Error comparing 49049 with 0n
Error comparing 49053 with 0n
Error comparing 49057 with 0n
Error comparing 50007 with 0n
Error comparing 51003 with 0n
Error comparing 51013 with 0n
Error comparing 51015 with 0n
Error comparing 51019 with 0n
Error comparing 51041 with 0n
Error comparing 51059 with 0n
Error comparing 51061 with 0n
Error comparing 51069 with 0n
Error comparing 51085 with 0n
Error comparing 51087 with 0n
Error comparing 51095 with 0n
Error comparing 51107 with 0n
Error comparing 51121 with 0n
Error comparing 51153 with 0n
Error comparing 51161 with 0n
Error comparing 51165 with 0n
Error comparing 51177 with 0n
Error comparing 51179 with 0n
Error comparing 51199 with 0n
Error comparing 51510 with 0n
Error comparing 51550 with 0n
Error comparing 51650 with 0n
Error comparing 51680 with 0n
Error comparing 51700 with 0n
Error comparing 51710 with 0n
Error comparing 51740 with 0n
Error comparing 51760 with 0n
Error comparing 51770 with 0n
Error comparing 51800 with 0n
Error comparing 51810 with 0n
Error comparing 53005 with 0n
Error comparing 53007 with 0n
Error comparing 53009 with 0n
Error comparing 53011 with 0n
Error comparing 53015 with 0n
Error comparing 53021 with 0n
Error comparing 53025 with 0n
Error comparing 53027 with 0n
Error comparing 53029 with 0n
Error comparing 53033 with 0n
Error comparing 53035 with 0n
Error comparing 53041 with 0n
Error comparing 53053 with 0n
Error comparing 53057 with 0n
Error comparing 53061 with 0n
Error comparing 53063 with 0n
Error comparing 53067 with 0n
Error comparing 53073 with 0n
Error comparing 53077 with 0n
Error comparing 54003 with 0n
Error comparing 54011 with 0n
Error comparing 54033 with 0n
Error comparing 54039 with 0n
Error comparing 54061 with 0n
Error comparing 54081 with 0n
Error comparing 54107 with 0n
Error comparing 55009 with 0n
Error comparing 55025 with 0n
Error comparing 55027 with 0n
Error comparing 55035 with 0n
Error comparing 55039 with 0n
Error comparing 55055 with 0n
Error comparing 55059 with 0n
Error comparing 55063 with 0n
Error comparing 55071 with 0n
Error comparing 55073 with 0n
Error comparing 55079 with 0n
Error comparing 55087 with 0n
Error comparing 55089 with 0n
Error comparing 55097 with 0n
Error comparing 55101 with 0n
Error comparing 55105 with 0n
Error comparing 55109 with 0n
Error comparing 55117 with 0n
Error comparing 55127 with 0n
Error comparing 55131 with 0n
Error comparing 55133 with 0n
Error comparing 55139 with 0n
Error comparing 55141 with 0n
Error comparing 56021 with 0n
Error comparing 56025 with 0n
Error comparing 72013 with 0n
Error comparing 72021 with 0n
Error comparing 72025 with 0n
Error comparing 72031 with 0n
Error comparing 72061 with 0n
Error comparing 72097 with 0n
Error comparing 72113 with 0n
Error comparing 72127 with 0n
Error comparing 72135 with 0n
Error comparing 72137 with 0n
Error comparing 72139 with 0n
here! nan
here! nan
here! nan
Error comparing 1003 with 0n
Error comparing 1015 with 0n
Error comparing 1043 with 0n
Error comparing 1049 with 0n
Error comparing 1051 with 0n
Error comparing 1055 with 0n
Error comparing 1069 with 0n
Error comparing 1073 with 0n
Error comparing 1077 with 0n
Error comparing 1081 with 0n
Error comparing 1083 with 0n
Error comparing 1089 with 0n
Error comparing 1095 with 0n
Error comparing 1097 with 0n
Error comparing 1101 with 0n
Error comparing 1103 with 0n
Error comparing 1115 with 0n
Error comparing 1117 with 0n
Error comparing 1121 with 0n
Error comparing 1125 with 0n
Error comparing 1127 with 0n
Error comparing 2020 with 0n
Error comparing 2090 with 0n
Error comparing 2170 with 0n
Error comparing 4001 with 0n
Error comparing 4003 with 0n
Error comparing 4005 with 0n
Error comparing 4013 with 0n
Error comparing 4015 with 0n
Error comparing 4017 with 0n
Error comparing 4019 with 0n
Error comparing 4021 with 0n
Error comparing 4025 with 0n
Error comparing 4027 with 0n
Error comparing 5007 with 0n
Error comparing 5031 with 0n
Error comparing 5045 with 0n
Error comparing 5051 with 0n
Error comparing 5069 with 0n
Error comparing 5085 with 0n
Error comparing 5119 with 0n
Error comparing 5125 with 0n
Error comparing 5131 with 0n
Error comparing 5143 with 0n
Error comparing 5145 with 0n
Error comparing 6001 with 0n
Error comparing 6007 with 0n
Error comparing 6013 with 0n
Error comparing 6017 with 0n
Error comparing 6019 with 0n
Error comparing 6023 with 0n
Error comparing 6025 with 0n
Error comparing 6029 with 0n
Error comparing 6031 with 0n
Error comparing 6033 with 0n
Error comparing 6037 with 0n
Error comparing 6039 with 0n
Error comparing 6041 with 0n
Error comparing 6045 with 0n
Error comparing 6047 with 0n
Error comparing 6053 with 0n
Error comparing 6055 with 0n
Error comparing 6057 with 0n
Error comparing 6059 with 0n
Error comparing 6061 with 0n
Error comparing 6065 with 0n
Error comparing 6067 with 0n
Error comparing 6071 with 0n
Error comparing 6073 with 0n
Error comparing 6075 with 0n
Error comparing 6077 with 0n
Error comparing 6079 with 0n
Error comparing 6081 with 0n
Error comparing 6083 with 0n
Error comparing 6085 with 0n
Error comparing 6087 with 0n
Error comparing 6089 with 0n
Error comparing 6095 with 0n
Error comparing 6097 with 0n
Error comparing 6099 with 0n
Error comparing 6101 with 0n
Error comparing 6107 with 0n
Error comparing 6111 with 0n
Error comparing 6113 with 0n
Error comparing 6115 with 0n
Error comparing 8001 with 0n
Error comparing 8005 with 0n
Error comparing 8013 with 0n
Error comparing 8031 with 0n
Error comparing 8035 with 0n
Error comparing 8041 with 0n
Error comparing 8059 with 0n
Error comparing 8069 with 0n
Error comparing 8077 with 0n
Error comparing 8101 with 0n
Error comparing 8123 with 0n
Error comparing 9001 with 0n
Error comparing 9003 with 0n
Error comparing 9005 with 0n
Error comparing 9007 with 0n
Error comparing 9009 with 0n
Error comparing 9011 with 0n
Error comparing 9013 with 0n
Error comparing 9015 with 0n
Error comparing 10001 with 0n
Error comparing 10003 with 0n
Error comparing 10005 with 0n
Error comparing 11001 with 0n
Error comparing 12001 with 0n
Error comparing 12005 with 0n
Error comparing 12009 with 0n
Error comparing 12011 with 0n
Error comparing 12015 with 0n
Error comparing 12017 with 0n
Error comparing 12019 with 0n
Error comparing 12021 with 0n
Error comparing 12023 with 0n
Error comparing 12031 with 0n
Error comparing 12033 with 0n
Error comparing 12035 with 0n
Error comparing 12053 with 0n
Error comparing 12055 with 0n
Error comparing 12057 with 0n
Error comparing 12061 with 0n
Error comparing 12069 with 0n
Error comparing 12071 with 0n
Error comparing 12073 with 0n
Error comparing 12081 with 0n
Error comparing 12083 with 0n
Error comparing 12085 with 0n
Error comparing 12086 with 0n
Error comparing 12087 with 0n
Error comparing 12089 with 0n
Error comparing 12091 with 0n
Error comparing 12095 with 0n
Error comparing 12097 with 0n
Error comparing 12099 with 0n
Error comparing 12101 with 0n
Error comparing 12103 with 0n
Error comparing 12105 with 0n
Error comparing 12107 with 0n
Error comparing 12109 with 0n
Error comparing 12111 with 0n
Error comparing 12113 with 0n
Error comparing 12115 with 0n
Error comparing 12117 with 0n
Error comparing 12119 with 0n
Error comparing 12127 with 0n
Error comparing 13013 with 0n
Error comparing 13015 with 0n
Error comparing 13021 with 0n
Error comparing 13031 with 0n
Error comparing 13045 with 0n
Error comparing 13051 with 0n
Error comparing 13057 with 0n
Error comparing 13059 with 0n
Error comparing 13063 with 0n
Error comparing 13067 with 0n
Error comparing 13073 with 0n
Error comparing 13077 with 0n
Error comparing 13089 with 0n
Error comparing 13095 with 0n
Error comparing 13097 with 0n
Error comparing 13113 with 0n
Error comparing 13115 with 0n
Error comparing 13117 with 0n
Error comparing 13121 with 0n
Error comparing 13127 with 0n
Error comparing 13135 with 0n
Error comparing 13139 with 0n
Error comparing 13151 with 0n
Error comparing 13153 with 0n
Error comparing 13185 with 0n
Error comparing 13215 with 0n
Error comparing 13217 with 0n
Error comparing 13223 with 0n
Error comparing 13245 with 0n
Error comparing 13247 with 0n
Error comparing 13285 with 0n
Error comparing 13295 with 0n
Error comparing 13297 with 0n
Error comparing 13313 with 0n
Error comparing 15001 with 0n
Error comparing 15003 with 0n
Error comparing 15007 with 0n
Error comparing 15009 with 0n
Error comparing 16001 with 0n
Error comparing 16005 with 0n
Error comparing 16019 with 0n
Error comparing 16027 with 0n
Error comparing 16055 with 0n
Error comparing 16083 with 0n
Error comparing 17001 with 0n
Error comparing 17019 with 0n
Error comparing 17031 with 0n
Error comparing 17037 with 0n
Error comparing 17043 with 0n
Error comparing 17089 with 0n
Error comparing 17091 with 0n
Error comparing 17093 with 0n
Error comparing 17097 with 0n
Error comparing 17099 with 0n
Error comparing 17111 with 0n
Error comparing 17113 with 0n
Error comparing 17115 with 0n
Error comparing 17119 with 0n
Error comparing 17143 with 0n
Error comparing 17161 with 0n
Error comparing 17163 with 0n
Error comparing 17167 with 0n
Error comparing 17179 with 0n
Error comparing 17183 with 0n
Error comparing 17197 with 0n
Error comparing 17199 with 0n
Error comparing 17201 with 0n
Error comparing 18003 with 0n
Error comparing 18005 with 0n
Error comparing 18019 with 0n
Error comparing 18035 with 0n
Error comparing 18039 with 0n
Error comparing 18043 with 0n
Error comparing 18053 with 0n
Error comparing 18057 with 0n
Error comparing 18059 with 0n
Error comparing 18063 with 0n
Error comparing 18067 with 0n
Error comparing 18081 with 0n
Error comparing 18085 with 0n
Error comparing 18089 with 0n
Error comparing 18091 with 0n
Error comparing 18095 with 0n
Error comparing 18097 with 0n
Error comparing 18105 with 0n
Error comparing 18109 with 0n
Error comparing 18127 with 0n
Error comparing 18141 with 0n
Error comparing 18157 with 0n
Error comparing 18163 with 0n
Error comparing 18167 with 0n
Error comparing 18177 with 0n
Error comparing 19013 with 0n
Error comparing 19049 with 0n
Error comparing 19061 with 0n
Error comparing 19103 with 0n
Error comparing 19113 with 0n
Error comparing 19153 with 0n
Error comparing 19155 with 0n
Error comparing 19163 with 0n
Error comparing 19169 with 0n
Error comparing 19193 with 0n
Error comparing 20015 with 0n
Error comparing 20045 with 0n
Error comparing 20091 with 0n
Error comparing 20103 with 0n
Error comparing 20161 with 0n
Error comparing 20173 with 0n
Error comparing 20177 with 0n
Error comparing 20209 with 0n
Error comparing 21015 with 0n
Error comparing 21029 with 0n
Error comparing 21037 with 0n
Error comparing 21047 with 0n
Error comparing 21059 with 0n
Error comparing 21067 with 0n
Error comparing 21093 with 0n
Error comparing 21111 with 0n
Error comparing 21117 with 0n
Error comparing 21145 with 0n
Error comparing 21151 with 0n
Error comparing 21195 with 0n
Error comparing 21227 with 0n
Error comparing 22005 with 0n
Error comparing 22015 with 0n
Error comparing 22017 with 0n
Error comparing 22019 with 0n
Error comparing 22033 with 0n
Error comparing 22045 with 0n
Error comparing 22051 with 0n
Error comparing 22055 with 0n
Error comparing 22057 with 0n
Error comparing 22063 with 0n
Error comparing 22071 with 0n
Error comparing 22073 with 0n
Error comparing 22079 with 0n
Error comparing 22097 with 0n
Error comparing 22103 with 0n
Error comparing 22105 with 0n
Error comparing 22109 with 0n
Error comparing 23001 with 0n
Error comparing 23003 with 0n
Error comparing 23005 with 0n
Error comparing 23011 with 0n
Error comparing 23019 with 0n
Error comparing 23031 with 0n
Error comparing 24001 with 0n
Error comparing 24003 with 0n
Error comparing 24005 with 0n
Error comparing 24009 with 0n
Error comparing 24013 with 0n
Error comparing 24015 with 0n
Error comparing 24017 with 0n
Error comparing 24021 with 0n
Error comparing 24025 with 0n
Error comparing 24027 with 0n
Error comparing 24031 with 0n
Error comparing 24033 with 0n
Error comparing 24037 with 0n
Error comparing 24043 with 0n
Error comparing 24045 with 0n
Error comparing 24510 with 0n
Error comparing 25001 with 0n
Error comparing 25003 with 0n
Error comparing 25005 with 0n
Error comparing 25009 with 0n
Error comparing 25011 with 0n
Error comparing 25013 with 0n
Error comparing 25015 with 0n
Error comparing 25017 with 0n
Error comparing 25021 with 0n
Error comparing 25023 with 0n
Error comparing 25025 with 0n
Error comparing 25027 with 0n
Error comparing 26005 with 0n
Error comparing 26017 with 0n
Error comparing 26021 with 0n
Error comparing 26025 with 0n
Error comparing 26037 with 0n
Error comparing 26045 with 0n
Error comparing 26049 with 0n
Error comparing 26055 with 0n
Error comparing 26065 with 0n
Error comparing 26073 with 0n
Error comparing 26075 with 0n
Error comparing 26077 with 0n
Error comparing 26081 with 0n
Error comparing 26087 with 0n
Error comparing 26091 with 0n
Error comparing 26093 with 0n
Error comparing 26099 with 0n
Error comparing 26103 with 0n
Error comparing 26111 with 0n
Error comparing 26115 with 0n
Error comparing 26121 with 0n
Error comparing 26125 with 0n
Error comparing 26139 with 0n
Error comparing 26145 with 0n
Error comparing 26147 with 0n
Error comparing 26155 with 0n
Error comparing 26159 with 0n
Error comparing 26161 with 0n
Error comparing 26163 with 0n
Error comparing 27003 with 0n
Error comparing 27019 with 0n
Error comparing 27037 with 0n
Error comparing 27053 with 0n
Error comparing 27109 with 0n
Error comparing 27123 with 0n
Error comparing 27137 with 0n
Error comparing 27139 with 0n
Error comparing 27141 with 0n
Error comparing 27145 with 0n
Error comparing 27163 with 0n
Error comparing 27171 with 0n
Error comparing 28033 with 0n
Error comparing 28035 with 0n
Error comparing 28047 with 0n
Error comparing 28049 with 0n
Error comparing 28059 with 0n
Error comparing 28067 with 0n
Error comparing 28075 with 0n
Error comparing 28081 with 0n
Error comparing 28089 with 0n
Error comparing 28121 with 0n
Error comparing 29019 with 0n
Error comparing 29021 with 0n
Error comparing 29031 with 0n
Error comparing 29037 with 0n

Error comparing 29043 with 0n
Error comparing 29047 with 0n
Error comparing 29051 with 0n
Error comparing 29071 with 0n
Error comparing 29077 with 0n
Error comparing 29095 with 0n
Error comparing 29097 with 0n
Error comparing 29099 with 0n
Error comparing 29165 with 0n
Error comparing 29183 with 0n
Error comparing 29187 with 0n
Error comparing 29189 with 0n
Error comparing 29510 with 0n
Error comparing 30013 with 0n
Error comparing 30029 with 0n
Error comparing 30031 with 0n
Error comparing 30063 with 0n
Error comparing 30111 with 0n
Error comparing 31055 with 0n
Error comparing 31109 with 0n
Error comparing 31153 with 0n
Error comparing 32003 with 0n
Error comparing 32031 with 0n
Error comparing 33005 with 0n
Error comparing 33009 with 0n
Error comparing 33011 with 0n
Error comparing 33013 with 0n
Error comparing 33015 with 0n
Error comparing 33017 with 0n
Error comparing 34001 with 0n
Error comparing 34003 with 0n
Error comparing 34005 with 0n
Error comparing 34007 with 0n
Error comparing 34009 with 0n
Error comparing 34011 with 0n
Error comparing 34013 with 0n
Error comparing 34015 with 0n
Error comparing 34017 with 0n
Error comparing 34019 with 0n
Error comparing 34021 with 0n
Error comparing 34023 with 0n
Error comparing 34025 with 0n
Error comparing 34027 with 0n
Error comparing 34029 with 0n
Error comparing 34031 with 0n
Error comparing 34033 with 0n
Error comparing 34035 with 0n
Error comparing 34037 with 0n
Error comparing 34039 with 0n
Error comparing 34041 with 0n
Error comparing 35001 with 0n
Error comparing 35005 with 0n
Error comparing 35013 with 0n
Error comparing 35031 with 0n
Error comparing 35043 with 0n
Error comparing 35045 with 0n
Error comparing 35049 with 0n
Error comparing 35061 with 0n
Error comparing 36001 with 0n
Error comparing 36005 with 0n
Error comparing 36007 with 0n
Error comparing 36009 with 0n
Error comparing 36011 with 0n
Error comparing 36013 with 0n
Error comparing 36015 with 0n
Error comparing 36019 with 0n
Error comparing 36027 with 0n
Error comparing 36029 with 0n
Error comparing 36045 with 0n
Error comparing 36047 with 0n
Error comparing 36051 with 0n
Error comparing 36053 with 0n
Error comparing 36055 with 0n
Error comparing 36059 with 0n
Error comparing 36061 with 0n
Error comparing 36063 with 0n
Error comparing 36065 with 0n
Error comparing 36067 with 0n
Error comparing 36069 with 0n
Error comparing 36071 with 0n
Error comparing 36075 with 0n
Error comparing 36079 with 0n
Error comparing 36081 with 0n
Error comparing 36083 with 0n
Error comparing 36085 with 0n
Error comparing 36087 with 0n
Error comparing 36089 with 0n
Error comparing 36091 with 0n
Error comparing 36093 with 0n
Error comparing 36101 with 0n
Error comparing 36103 with 0n
Error comparing 36105 with 0n
Error comparing 36109 with 0n
Error comparing 36111 with 0n
Error comparing 36113 with 0n
Error comparing 36117 with 0n
Error comparing 36119 with 0n
Error comparing 37001 with 0n
Error comparing 37019 with 0n
Error comparing 37021 with 0n
Error comparing 37023 with 0n
Error comparing 37025 with 0n
Error comparing 37027 with 0n
Error comparing 37031 with 0n
Error comparing 37035 with 0n
Error comparing 37045 with 0n
Error comparing 37049 with 0n
Error comparing 37051 with 0n
Error comparing 37057 with 0n
Error comparing 37063 with 0n
Error comparing 37067 with 0n
Error comparing 37071 with 0n
Error comparing 37081 with 0n
Error comparing 37085 with 0n
Error comparing 37089 with 0n
Error comparing 37097 with 0n
Error comparing 37101 with 0n
Error comparing 37109 with 0n
Error comparing 37119 with 0n
Error comparing 37125 with 0n
Error comparing 37127 with 0n
Error comparing 37129 with 0n
Error comparing 37133 with 0n
Error comparing 37135 with 0n
Error comparing 37147 with 0n
Error comparing 37151 with 0n
Error comparing 37155 with 0n
Error comparing 37157 with 0n
Error comparing 37159 with 0n
Error comparing 37161 with 0n
Error comparing 37171 with 0n
Error comparing 37179 with 0n
Error comparing 37183 with 0n
Error comparing 37191 with 0n
Error comparing 37193 with 0n
Error comparing 37195 with 0n
Error comparing 38015 with 0n
Error comparing 38017 with 0n
Error comparing 38035 with 0n
Error comparing 39003 with 0n
Error comparing 39007 with 0n
Error comparing 39013 with 0n
Error comparing 39017 with 0n
Error comparing 39023 with 0n
Error comparing 39025 with 0n
Error comparing 39029 with 0n
Error comparing 39035 with 0n
Error comparing 39041 with 0n
Error comparing 39043 with 0n
Error comparing 39045 with 0n
Error comparing 39049 with 0n
Error comparing 39055 with 0n
Error comparing 39057 with 0n
Error comparing 39061 with 0n
Error comparing 39063 with 0n
Error comparing 39081 with 0n
Error comparing 39085 with 0n
Error comparing 39089 with 0n
Error comparing 39093 with 0n
Error comparing 39095 with 0n
Error comparing 39099 with 0n
Error comparing 39101 with 0n
Error comparing 39103 with 0n
Error comparing 39109 with 0n
Error comparing 39113 with 0n
Error comparing 39119 with 0n
Error comparing 39133 with 0n
Error comparing 39139 with 0n
Error comparing 39141 with 0n
Error comparing 39145 with 0n
Error comparing 39151 with 0n
Error comparing 39153 with 0n
Error comparing 39155 with 0n
Error comparing 39157 with 0n
Error comparing 39165 with 0n
Error comparing 39169 with 0n
Error comparing 39173 with 0n
Error comparing 40017 with 0n
Error comparing 40027 with 0n
Error comparing 40031 with 0n
Error comparing 40037 with 0n
Error comparing 40101 with 0n
Error comparing 40109 with 0n
Error comparing 40119 with 0n
Error comparing 40125 with 0n
Error comparing 40131 with 0n
Error comparing 40143 with 0n
Error comparing 40145 with 0n
Error comparing 41003 with 0n
Error comparing 41005 with 0n
Error comparing 41017 with 0n
Error comparing 41019 with 0n
Error comparing 41029 with 0n
Error comparing 41033 with 0n
Error comparing 41035 with 0n
Error comparing 41039 with 0n
Error comparing 41043 with 0n
Error comparing 41047 with 0n
Error comparing 41051 with 0n
Error comparing 41053 with 0n
Error comparing 41059 with 0n
Error comparing 41067 with 0n
Error comparing 41071 with 0n
Error comparing 42001 with 0n
Error comparing 42003 with 0n
Error comparing 42005 with 0n
Error comparing 42007 with 0n
Error comparing 42011 with 0n
Error comparing 42013 with 0n
Error comparing 42017 with 0n
Error comparing 42019 with 0n
Error comparing 42021 with 0n
Error comparing 42025 with 0n
Error comparing 42027 with 0n
Error comparing 42029 with 0n
Error comparing 42033 with 0n
Error comparing 42037 with 0n
Error comparing 42039 with 0n
Error comparing 42041 with 0n
Error comparing 42043 with 0n
Error comparing 42045 with 0n
Error comparing 42049 with 0n
Error comparing 42051 with 0n
Error comparing 42055 with 0n
Error comparing 42063 with 0n
Error comparing 42069 with 0n
Error comparing 42071 with 0n
Error comparing 42073 with 0n
Error comparing 42075 with 0n
Error comparing 42077 with 0n
Error comparing 42079 with 0n
Error comparing 42081 with 0n
Error comparing 42085 with 0n
Error comparing 42089 with 0n
Error comparing 42091 with 0n
Error comparing 42095 with 0n
Error comparing 42097 with 0n
Error comparing 42101 with 0n
Error comparing 42107 with 0n
Error comparing 42111 with 0n
Error comparing 42125 with 0n
Error comparing 42129 with 0n
Error comparing 42133 with 0n
Error comparing 44003 with 0n
Error comparing 44005 with 0n
Error comparing 44007 with 0n
Error comparing 44009 with 0n
Error comparing 45003 with 0n
Error comparing 45007 with 0n
Error comparing 45013 with 0n
Error comparing 45015 with 0n
Error comparing 45019 with 0n
Error comparing 45031 with 0n
Error comparing 45035 with 0n
Error comparing 45041 with 0n
Error comparing 45045 with 0n
Error comparing 45047 with 0n
Error comparing 45051 with 0n
Error comparing 45057 with 0n
Error comparing 45059 with 0n
Error comparing 45063 with 0n
Error comparing 45073 with 0n
Error comparing 45075 with 0n
Error comparing 45077 with 0n
Error comparing 45079 with 0n
Error comparing 45083 with 0n
Error comparing 45085 with 0n
Error comparing 45091 with 0n
Error comparing 46099 with 0n
Error comparing 46103 with 0n
Error comparing 47001 with 0n
Error comparing 47009 with 0n
Error comparing 47011 with 0n
Error comparing 47037 with 0n
Error comparing 47059 with 0n
Error comparing 47065 with 0n
Error comparing 47093 with 0n
Error comparing 47113 with 0n
Error comparing 47119 with 0n
Error comparing 47125 with 0n
Error comparing 47141 with 0n
Error comparing 47147 with 0n
Error comparing 47149 with 0n
Error comparing 47155 with 0n
Error comparing 47157 with 0n
Error comparing 47163 with 0n
Error comparing 47165 with 0n
Error comparing 47179 with 0n
Error comparing 47187 with 0n
Error comparing 47189 with 0n
Error comparing 48005 with 0n
Error comparing 48021 with 0n
Error comparing 48027 with 0n
Error comparing 48029 with 0n
Error comparing 48037 with 0n
Error comparing 48039 with 0n
Error comparing 48041 with 0n
Error comparing 48061 with 0n
Error comparing 48085 with 0n
Error comparing 48091 with 0n
Error comparing 48099 with 0n
Error comparing 48113 with 0n
Error comparing 48121 with 0n
Error comparing 48135 with 0n
Error comparing 48139 with 0n
Error comparing 48141 with 0n
Error comparing 48157 with 0n
Error comparing 48167 with 0n
Error comparing 48181 with 0n
Error comparing 48183 with 0n
Error comparing 48187 with 0n
Error comparing 48201 with 0n
Error comparing 48203 with 0n
Error comparing 48209 with 0n
Error comparing 48213 with 0n
Error comparing 48215 with 0n
Error comparing 48231 with 0n
Error comparing 48245 with 0n
Error comparing 48251 with 0n
Error comparing 48257 with 0n
Error comparing 48291 with 0n
Error comparing 48303 with 0n
Error comparing 48309 with 0n
Error comparing 48329 with 0n
Error comparing 48339 with 0n
Error comparing 48355 with 0n
Error comparing 48361 with 0n
Error comparing 48367 with 0n
Error comparing 48375 with 0n
Error comparing 48381 with 0n
Error comparing 48397 with 0n
Error comparing 48409 with 0n
Error comparing 48423 with 0n
Error comparing 48439 with 0n
Error comparing 48441 with 0n
Error comparing 48451 with 0n
Error comparing 48453 with 0n
Error comparing 48469 with 0n
Error comparing 48471 with 0n
Error comparing 48479 with 0n
Error comparing 48485 with 0n
Error comparing 48491 with 0n
Error comparing 49005 with 0n
Error comparing 49011 with 0n
Error comparing 49035 with 0n
Error comparing 49049 with 0n
Error comparing 49053 with 0n
Error comparing 49057 with 0n
Error comparing 50007 with 0n
Error comparing 51003 with 0n
Error comparing 51013 with 0n
Error comparing 51015 with 0n
Error comparing 51019 with 0n
Error comparing 51041 with 0n
Error comparing 51059 with 0n
Error comparing 51061 with 0n
Error comparing 51069 with 0n
Error comparing 51085 with 0n
Error comparing 51087 with 0n
Error comparing 51095 with 0n
Error comparing 51107 with 0n
Error comparing 51121 with 0n
Error comparing 51153 with 0n
Error comparing 51161 with 0n
Error comparing 51165 with 0n
Error comparing 51177 with 0n
Error comparing 51179 with 0n
Error comparing 51199 with 0n
Error comparing 51510 with 0n
Error comparing 51550 with 0n
Error comparing 51650 with 0n
Error comparing 51680 with 0n
Error comparing 51700 with 0n
Error comparing 51710 with 0n
Error comparing 51740 with 0n
Error comparing 51760 with 0n
Error comparing 51770 with 0n
Error comparing 51800 with 0n
Error comparing 51810 with 0n
Error comparing 53005 with 0n
Error comparing 53007 with 0n
Error comparing 53009 with 0n

Error comparing 53011 with 0n
Error comparing 53015 with 0n
Error comparing 53021 with 0n
Error comparing 53025 with 0n
Error comparing 53027 with 0n
Error comparing 53029 with 0n
Error comparing 53033 with 0n
Error comparing 53035 with 0n
Error comparing 53041 with 0n
Error comparing 53053 with 0n
Error comparing 53057 with 0n
Error comparing 53061 with 0n
Error comparing 53063 with 0n
Error comparing 53067 with 0n
Error comparing 53073 with 0n
Error comparing 53077 with 0n
Error comparing 54003 with 0n
Error comparing 54011 with 0n
Error comparing 54033 with 0n
Error comparing 54039 with 0n
Error comparing 54061 with 0n
Error comparing 54081 with 0n
Error comparing 54107 with 0n
Error comparing 55009 with 0n
Error comparing 55025 with 0n
Error comparing 55027 with 0n
Error comparing 55035 with 0n
Error comparing 55039 with 0n
Error comparing 55055 with 0n
Error comparing 55059 with 0n
Error comparing 55063 with 0n
Error comparing 55071 with 0n
Error comparing 55073 with 0n
Error comparing 55079 with 0n
Error comparing 55087 with 0n
Error comparing 55089 with 0n
Error comparing 55097 with 0n
Error comparing 55101 with 0n
Error comparing 55105 with 0n
Error comparing 55109 with 0n
Error comparing 55117 with 0n
Error comparing 55127 with 0n
Error comparing 55131 with 0n
Error comparing 55133 with 0n
Error comparing 55139 with 0n
Error comparing 55141 with 0n
Error comparing 56021 with 0n
Error comparing 56025 with 0n
Error comparing 72013 with 0n
Error comparing 72021 with 0n
Error comparing 72025 with 0n
Error comparing 72031 with 0n
Error comparing 72061 with 0n
Error comparing 72097 with 0n
Error comparing 72113 with 0n
Error comparing 72127 with 0n
Error comparing 72135 with 0n
Error comparing 72137 with 0n
Error comparing 72139 with 0n
here! nan
here! nan
here! nan
here! nan
here! nan
here! nan
here! nan
here! nan
here! nan
here! nan
here! nan
here! nan
here! nan
here! nan
here! nan
here! nan
here! nan
here! nan
here! nan
here! nan
here! nan
here! nan
here! nan
here! nan
here! nan
here! nan
here! nan
here! nan
here! nan
here! nan
here! nan
here! nan
here! nan
here! nan
here! nan
here! nan
here! nan
here! nan
here! nan
here! nan
here! nan
here! nan
here! nan
here! nan
here! nan
here! nan
here! nan

In [26]:
fips_df.shape[0] - fips_df['gran'].isna().sum() # see how many addresses have census data

459

In [27]:
fips_df['xobsyr_0'] = fips_df['xobsyr_0'].astype(int)
fips_df.head()

,block_FIPS,county_FIPS,xobsyr_0,Address,gran,%_U18g,%_female_householdg,%_unemployedg,%_public_assistanceg,%_povertyg
1,390351059002009,39035,2006,"1276 West Third St. #400, Cleveland, OH",0.0,0.0,1.0,0.0,0.0,0.0
6,191030003012027,19103,2006,"100 Oakdale Campus - M319, Iowa City, IA",0.0,0.0,1.0,0.0,0.0,0.0
18,211110083002011,21111,2006,"1220 Bardstown Rd, Louisville, KY",0.0,0.0,1.0,0.0,0.0,0.0
21,040190007003001,04019,2006,"3130 E Broadway Blvd, Tucson, AZ",0.0,0.0,1.0,0.0,0.0,0.0
27,481410043124008,48141,2008,"1111 Barranca Dr., Suite 800, El Paso, TX",0.0,1.0,1.0,0.0,0.0,1.0

In [28]:
df = df.merge(fips_df, on=['Address', 'xobsyr_0'], how='left')
df.head()

,Unnamed: 0,Unnamed: 0.1,ID,State,City,agyaddr,xobsyr_0,Illicit_Days5,Illicit_Cens5,female_cd,nonwhite_cd,unemplmt_cd,prsatx_cd,gvsg_cd,CWSg_0_cd,srprobg_cd,dssg_0_cd,epsg_0_cd,adhdg_0_cd,cdsg_0_cd,cjsig_0_cd,lrig_0_cd,srig_0_cd,SESg_0_cd,r4ag_0_cd,nonillicit_flag,primsev_cd_1,primsev_cd_2,primsev_cd_3,primsev_cd_4,primsev_cd_5,primsev_cd_6,B2a_0g,SUDSy_0,SDSl_0,Address,lat,lng,state_name,county_FIPS_x,block_FIPS_x,murder_numg,block_FIPS_y,county_FIPS_y,gran,%_U18g,%_female_householdg,%_unemployedg,%_public_assistanceg,%_povertyg
0,0,1,857,OH,Cleveland,1276 West Third St. #400,2005,365,0,0,0,0,0,2,0,0,1,1,1,1,0,1,2,0,1,1,1,0,0,0,0,0,0,0,0,"1276 West Third St. #400, Cleveland, OH",41.419286,-81.701695,Ohio,39035.0,3.903511e+14,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,2,929,OH,Cleveland,1276 West Third St. #400,2006,354,0,0,0,0,0,1,0,1,0,1,0,1,1,0,1,0,2,1,1,0,0,0,0,0,0,3,2,"1276 West Third St. #400, Cleveland, OH",41.419286,-81.701695,Ohio,39035.0,3.903511e+14,0,390351059002009,39035,0.0,0.0,1.0,0.0,0.0,0.0
2,2,3,951,OH,Cleveland,1276 West Third St. #400,2006,365,0,0,0,0,0,0,0,1,0,0,0,0,1,0,1,0,2,1,0,0,1,0,0,0,0,2,1,"1276 West Third St. #400, Cleveland, OH",41.419286,-81.701695,Ohio,39035.0,3.903511e+14,0,390351059002009,39035,0.0,0.0,1.0,0.0,0.0,0.0
3,3,4,1032,OH,Cleveland,1276 West Third St. #400,2006,365,0,0,0,0,0,2,0,1,1,1,1,1,0,2,1,0,2,1,0,0,1,0,0,0,0,2,1,"1276 West Third St. #400, Cleveland, OH",41.419286,-81.701695,Ohio,39035.0,3.903511e+14,0,390351059002009,39035,0.0,0.0,1.0,0.0,0.0,0.0
4,4,5,1039,OH,Cleveland,1276 West Third St. #400,2004,365,0,0,0,0,0,0,0,0,1,0,0,1,1,2,1,0,2,0,0,1,0,0,0,0,0,0,0,"1276 West Third St. #400, Cleveland, OH",41.419286,-81.701695,Ohio,39035.0,3.903511e+14,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [29]:
df.shape[0] - df['gran'].isna().sum() # see how many patients have census data

15376

In [30]:
df.isna().sum()

Unnamed: 0                 0
Unnamed: 0.1               0
ID                         0
State                      0
City                       0
agyaddr                    0
xobsyr_0                   0
Illicit_Days5              0
Illicit_Cens5              0
female_cd                  0
nonwhite_cd                0
unemplmt_cd                0
prsatx_cd                  0
gvsg_cd                    0
CWSg_0_cd                  0
srprobg_cd                 0
dssg_0_cd                  0
epsg_0_cd                  0
adhdg_0_cd                 0
cdsg_0_cd                  0
cjsig_0_cd                 0
lrig_0_cd                  0
srig_0_cd                  0
SESg_0_cd                  0
r4ag_0_cd                  0
nonillicit_flag            0
primsev_cd_1               0
primsev_cd_2               0
primsev_cd_3               0
primsev_cd_4               0
primsev_cd_5               0
primsev_cd_6               0
B2a_0g                     0
SUDSy_0                    0
SDSl_0                     0
Address                    0
lat                        0
lng                        0
state_name                43
county_FIPS_x             43
block_FIPS_x              43
murder_numg             8342
block_FIPS_y            5616
county_FIPS_y           5616
gran                    5888
%_U18g                  5888
%_female_householdg     5888
%_unemployedg           5888
%_public_assistanceg    5888
%_povertyg              5888
dtype: int64

In [31]:
df.shape

(21264, 50)

In [32]:
temp = df.dropna(subset=['murder_numg', 'gran'])
temp.shape

(10025, 50)

In [33]:
temp.isna().sum()

Unnamed: 0              0
Unnamed: 0.1            0
ID                      0
State                   0
City                    0
agyaddr                 0
xobsyr_0                0
Illicit_Days5           0
Illicit_Cens5           0
female_cd               0
nonwhite_cd             0
unemplmt_cd             0
prsatx_cd               0
gvsg_cd                 0
CWSg_0_cd               0
srprobg_cd              0
dssg_0_cd               0
epsg_0_cd               0
adhdg_0_cd              0
cdsg_0_cd               0
cjsig_0_cd              0
lrig_0_cd               0
srig_0_cd               0
SESg_0_cd               0
r4ag_0_cd               0
nonillicit_flag         0
primsev_cd_1            0
primsev_cd_2            0
primsev_cd_3            0
primsev_cd_4            0
primsev_cd_5            0
primsev_cd_6            0
B2a_0g                  0
SUDSy_0                 0
SDSl_0                  0
Address                 0
lat                     0
lng                     0
state_name              0
county_FIPS_x           0
block_FIPS_x            0
murder_numg             0
block_FIPS_y            0
county_FIPS_y           0
gran                    0
%_U18g                  0
%_female_householdg     0
%_unemployedg           0
%_public_assistanceg    0
%_povertyg              0
dtype: int64

In [34]:
df.head()

,Unnamed: 0,Unnamed: 0.1,ID,State,City,agyaddr,xobsyr_0,Illicit_Days5,Illicit_Cens5,female_cd,nonwhite_cd,unemplmt_cd,prsatx_cd,gvsg_cd,CWSg_0_cd,srprobg_cd,dssg_0_cd,epsg_0_cd,adhdg_0_cd,cdsg_0_cd,cjsig_0_cd,lrig_0_cd,srig_0_cd,SESg_0_cd,r4ag_0_cd,nonillicit_flag,primsev_cd_1,primsev_cd_2,primsev_cd_3,primsev_cd_4,primsev_cd_5,primsev_cd_6,B2a_0g,SUDSy_0,SDSl_0,Address,lat,lng,state_name,county_FIPS_x,block_FIPS_x,murder_numg,block_FIPS_y,county_FIPS_y,gran,%_U18g,%_female_householdg,%_unemployedg,%_public_assistanceg,%_povertyg
0,0,1,857,OH,Cleveland,1276 West Third St. #400,2005,365,0,0,0,0,0,2,0,0,1,1,1,1,0,1,2,0,1,1,1,0,0,0,0,0,0,0,0,"1276 West Third St. #400, Cleveland, OH",41.419286,-81.701695,Ohio,39035.0,3.903511e+14,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,2,929,OH,Cleveland,1276 West Third St. #400,2006,354,0,0,0,0,0,1,0,1,0,1,0,1,1,0,1,0,2,1,1,0,0,0,0,0,0,3,2,"1276 West Third St. #400, Cleveland, OH",41.419286,-81.701695,Ohio,39035.0,3.903511e+14,0,390351059002009,39035,0.0,0.0,1.0,0.0,0.0,0.0
2,2,3,951,OH,Cleveland,1276 West Third St. #400,2006,365,0,0,0,0,0,0,0,1,0,0,0,0,1,0,1,0,2,1,0,0,1,0,0,0,0,2,1,"1276 West Third St. #400, Cleveland, OH",41.419286,-81.701695,Ohio,39035.0,3.903511e+14,0,390351059002009,39035,0.0,0.0,1.0,0.0,0.0,0.0
3,3,4,1032,OH,Cleveland,1276 West Third St. #400,2006,365,0,0,0,0,0,2,0,1,1,1,1,1,0,2,1,0,2,1,0,0,1,0,0,0,0,2,1,"1276 West Third St. #400, Cleveland, OH",41.419286,-81.701695,Ohio,39035.0,3.903511e+14,0,390351059002009,39035,0.0,0.0,1.0,0.0,0.0,0.0
4,4,5,1039,OH,Cleveland,1276 West Third St. #400,2004,365,0,0,0,0,0,0,0,0,1,0,0,1,1,2,1,0,2,0,0,1,0,0,0,0,0,0,0,"1276 West Third St. #400, Cleveland, OH",41.419286,-81.701695,Ohio,39035.0,3.903511e+14,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [35]:
df.to_csv('data_superset_stratified.csv')

In [36]:
# print out total notebook execution time
total_seconds = int(time.time() - start_time)
minutes = total_seconds // 60
seconds = total_seconds % 60
print("--- " + str(minutes) + " minutes " + str(seconds) + " seconds ---")

--- 26 minutes 47 seconds ---